### ISSUE TITLE
ui grid causing 100% cpu

### ISSUE THREAD

**Issue by jmls** [angular-ui/ng-grid#2851] opened 2015-02-26 10:02 UTC
just including ui-grid in the angular dependencies for an app causing my system to go to 100% cpu

I've collected the cpu profile from chrome after refreshing the page 

```Javascript
var app = angular.module('app', 'ui.grid','ui.grid.autoResize','ui.grid.resizeColumns']);
```
![image](https://cloud.githubusercontent.com/assets/929523/6389716/82553128-bd9e-11e4-9c98-bb197c99448c.png)

is this a known problem ?

Running chrome 40.0.2214.115 (64-bit) on ubuntu 14.10

**Comment by jmls** [comment] 2015-02-26 10:05
[edit]
interestingly enough, if I remove ui.grid.autoResize, the problem goes away

```Javascript
var app = angular.module('app', ['ui.grid','ui.grid.resizeColumns']);
```

**Comment by cookednoodles** [comment] 2015-02-26 10:22
autoresize is run every 250ms, depending on how complicated your DOM is and the elements around, this can be very intensive.

**Comment by jmls** [comment] 2015-02-26 10:42
I have no grids at all. I just included the dependencies ;)

**Comment by c0bra** [comment] 2015-02-26 13:44
That's flippin' strange.

**Comment by c0bra** [comment] 2015-02-26 13:58
Just including the dependencies should do nothing. The measurements will only happen if the `ui-grid-auto-resize` directive was applied to a grid element.

**Comment by jmls** [comment] 2015-02-26 14:06
and now, I can't reproduce it .. previously, all I needed to do was to include/take out the 'ui.grid.autoResize' dependency and it would go from 100% to 0% consistently. 

I'll keep an eye out, and report back.

**Comment by c0bra** [comment] 2015-03-13 15:26
@jmls any luck reproducing it?

**Comment by jmls** [comment] 2015-03-13 15:46
nope. But the resizeColumns does cause mucho cpu usage so i've taken them out

**Comment by c0bra** [comment] 2015-03-30 20:41
Well that's a separate issue, if you want to file one for that please go ahead. I'll close this one as we couldn't reproduce it.

**Closed by c0bra** 2015-03-30 20:41 UTC
Labels: peformance
