### ISSUE TITLE
Pagination and Expandable together when 100% cause weird styling

### ISSUE THREAD

**Issue by jrgleason** [angular-ui/ng-grid#2654] opened 2015-01-27 21:31 UTC
I have an example here...

http://plnkr.co/edit/Mcu1bmxRIAfBtFkMMGi3?p=preview

basically I have pagination and expanding and when I scroll all the way down if I open and close the bottom it leaves white space until I scroll or some other movement.

**Comment by jpuri** [comment] 2015-02-02 06:53
The problem is not with Expandable or Pagination, but its a rather known bug that scrolling at times gives this weird behavior with expandable grids. Check #2488.

**Comment by PaulL1** [comment] 2015-03-28 08:54
This appears resolved - could you confirm?

**Comment by PaulL1** [comment] 2015-04-12 07:00
Looks fixed, no further comment after 2 weeks, closing.

**Closed by PaulL1** 2015-04-12 07:00 UTC
Labels: waiting-response
