### ISSUE TITLE
Columns disappear after filtering

### ISSUE THREAD

**Issue by ComeOutToPlay** [angular-ui/ng-grid#3006] opened 2015-03-13 13:28 UTC
When you have a grid with a lot of columns and an horizontal scroll bar is necessary, there is a rendering problem when you use input filters. 

If you filter a column and the input filter has the focus, but it is not visible completely, the last column at the right disappears.

Here is the plunkr
http://plnkr.co/edit/lEUL8bK6GAMTvwZv9BtX?p=preview

It happens when you test it from plunkr preview window or when you launch the preview in a separate window.

Please observe that the column has the focus, but it is not displayed completely:
![primero](https://cloud.githubusercontent.com/assets/5622990/6639095/543c973a-c96b-11e4-8360-2a99398fecbb.jpg)

Please observe that the column Childrens disappears:
![segundo](https://cloud.githubusercontent.com/assets/5622990/6639101/5ac28330-c96b-11e4-84de-5be169a34284.jpg)

PD: It also happens at 

http://ui-grid.info/docs/#/tutorial/401_AllFeatures

**Comment by c0bra** [comment] 2015-03-13 14:55
Looks like the browser is scrolling the header container automatically to make sure the input is visible, but the grid doesn't have the header container hooked up to broadcast scroll events.

**Comment by PaulL1** [comment] 2015-03-13 18:41
Duplicate of #2573

**Comment by ComeOutToPlay** [comment] 2015-03-13 19:05
Hello Paul.

I think it is a different test #2573 and #3006. I did not do a tab test. 

Thanks

**Comment by PaulL1** [comment] 2015-03-13 19:22
OK, but I think it has the same root cause.

**Comment by PaulL1** [comment] 2015-04-12 06:50
This looks to be fixed in the latest code base.  Closing.

**Closed by PaulL1** 2015-04-12 06:50 UTC
Labels: waiting-response
