### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by gunjanr17** [angular-ui/ng-grid#2646] opened 2015-01-27 10:08 UTC
What versions of .xls and .xlsx the current csv export is compatible with?

**Comment by PaulL1** [comment] 2015-01-27 12:28
None - it exports in csv format, which excel is capable of importing (and on most machines where excel is installed, will open in excel automatically)

**Comment by cookednoodles** [comment] 2015-01-27 14:34
However, in some european countries it won't open correctly. Accents and special characters will be messed up in excel, because of utf-8 not being set. Excel will also want a semi-colon as a delimiter, not a comma.

**Comment by gunjanr17** [comment] 2015-01-27 15:20
I think there was already a issue logged for adding UTF-8 support to CSV which is closed, so I suppose we already have UTF-8  being set. 
Does CSV export consider the locale settings for delimiter?

**Comment by PaulL1** [comment] 2015-01-27 22:28
There is an option to override the delimiter, and I thought the character set got changed.  However, when we redid the download link we may have lost that.

**Comment by cookednoodles** [comment] 2015-01-30 09:56
It seems it was removed again in ttps://github.com/angular-ui/ng-grid/commit/aad0bd6156fcf3b8930f4291fc1588e7864eea4c I have no idea on the best way to do this as it appears that each application behaves differently.

**Comment by PaulL1** [comment] 2015-01-30 11:59
I did the change in that commit, and at the time I did it that first character was turning up in the CSV import as an unprintable in the first cell of the CSV.  Taking it out fixed the problem.  I think I worked out that the "\ufeff" was just another way to set character set, and the change to the download link in #2931 I added `var strMimeType = 'application/octet-stream;charset=utf-8';`, which also sets the character set.  The two I think were conflicting.

So I think that we're still set to utf-8.

**Comment by PaulL1** [comment] 2015-02-14 00:23
I think excel is quite happy with a comma as delimiter, as that is the csv specification.  Is anyone using rc19 and can confirm that it is or is not utf-8?

**Comment by c0bra** [comment] 2015-02-27 16:01
`file -bi filename` reports "text/plain; charset=us-ascii", but that's after downloading on Windows and copying over Samba to my linux machine. There's no really set-in-stone way to tell the correct encoding of a file.

I'm going to go ahead and close this. If the encoding or something else is still a problem then a new issue can be opened.

**Comment by Cog-g** [comment] 2015-03-08 00:17
I can confirm that I have the same problem of encoding. And reversing https://github.com/angular-ui/ng-grid/commit/aad0bd6156fcf3b8930f4291fc1588e7864eea4c resolve this problem.

**Comment by PaulL1** [comment] 2015-03-09 02:43
OK, the problem here is a mix of compatibility.  If we take off the BOM (which indicates that we're utf) then some applications don't import utf characters.  If we include the BOM then some versions of Excel don't recognise it, so we get `ï»¿"Name"` in the first cell.

According to http://stackoverflow.com/questions/6002256/is-it-possible-to-force-excel-recognize-utf-8-csv-files-automatically and http://stackoverflow.com/questions/155097/microsoft-excel-mangles-diacritics-in-csv-files, the problem is only with earlier versions of excel (and apparently, based on my own experience, the OSX version of Excel).

I'm erring on the side of default handling it right, and adding an option for `exporterOlderExcelCompatibility`.

**Closed** 2015-03-09 03:02 UTC
Labels: in progress, waiting-response
