### ISSUE TITLE
Modifying columnDef.enableFiltering has no effect after the grid has rendered

### ISSUE THREAD

**Issue by axelstudios** [angular-ui/ng-grid#2544] opened 2015-01-14 04:18 UTC
Even with calling `notifyDataChange`, disabling `enableFiltering` on a columnDef does not update the column header to remove the filters.  Changing something like displayName and then calling notifyDataChange works, but modifying enableFiltering does not.  I really hope I missed something, but it looks like a bug.

Example:
http://plnkr.co/edit/ILZh6kosopnHqGtNjZ3c?p=preview

More details:  In the 'ui-grid/uiGridHeaderCell' template, `filterable` is still resolving to true

Workaround:  Create a custom headerCellTemplate, and replace `filterable` with `grid.options.enableFiltering && col.enableFiltering`

**Comment by PaulL1** [comment] 2015-01-14 19:46
This is a duplicate of #2067

**Closed by PaulL1** 2015-01-14 19:46 UTC
