### ISSUE TITLE
Scrolling on a macbook trackpad is very sensitive.

### ISSUE THREAD

**Issue by roguezedd** [angular-ui/ng-grid#2767] opened 2015-02-13 02:00 UTC
Scrolling on a macbook trackpad is very sensitive. Very small movements result in scrolling a large number of rows. When I plug in my mouse and use the scroll wheel, everything works pretty well. However, when I unplug the mouse, the trackpad is pretty sensitive, and it is very difficult to navigate the grid.

**Comment by PaulL1** [comment] 2015-02-13 23:28
Duplicate of #937.  The issue here is that the one set of scrolling code doesn't work very well across both windows and OSX trackpad.  There is work underway on this at the moment.

**Closed by PaulL1** 2015-02-13 23:28 UTC
