### ISSUE TITLE
[3.0][Scroll] table column are not under header column, when I use horizontal scrollbar

### ISSUE THREAD

**Issue by MariMax** [angular-ui/ng-grid#2636] opened 2015-01-26 11:01 UTC
[example](http://plnkr.co/edit/tPER4Qwckk9AwO3sqBG3?p=preview), [screenshoot](https://yadi.sk/i/trLlxVyeeEzzK)

**Comment by c0bra** [comment] 2015-01-26 15:02
Thanks for the report but this appears to be a duplicate of #2592; closing.

**Closed by c0bra** 2015-01-26 15:02 UTC

**Comment by kenaths** [comment] 2017-03-10 08:36
Set enableVerticalScrollbar to true, It'll fix the issue.

        $scope.gridOptions = {
            enableVerticalScrollbar: 1,
            ..............
        }
