### ISSUE TITLE
Grid header auto adjust issue.

### ISSUE THREAD

**Issue by debayan31** [angular-ui/ng-grid#3319] opened 2015-04-20 12:31 UTC
By default in my grid : enableFiltering: false

When I am calling toggleFiltering then filtering panel in coming correctly.But when I am once again calling toggleFiltering for hiding filters then filtering part is disappearing but width of header is not auto adjusting<See RED highlighted part in screenshot >. 

$scope.toggleFiltering = function () {
            $scope.gridOptions.enableFiltering = !$scope.gridOptions.enableFiltering;
            $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.COLUMN);
        };

![screenshot](https://cloud.githubusercontent.com/assets/11749797/7229951/e7c1cd2a-e786-11e4-8064-0e678c739cee.jpg)

**Comment by PaulL1** [comment] 2015-04-20 20:51
Are you able to provide a plunker?  It works on the tutorial still: http://ui-grid.info/docs/#/tutorial/103_filtering, so there must be something different with your code.

**Comment by debayan31** [comment] 2015-05-18 10:05
PauL is it possible to provide any mail ID in which I will send whole code base so that you can just able to get exact problem when ever it is running locally.

**Comment by debayan31** [comment] 2015-05-18 10:34
PauL Issue is coming in below scenario

Filtering part Not coming when ::

<div id="grid" ui-grid="gridOptions" class="gridFlatStructure " ui-grid="gridOptions" ui-grid-edit 
                         ui-grid-selection>
</div>


But filtering part coming when :: (After deleting ui-grid-selection)

<div id="grid" ui-grid="gridOptions" class="gridFlatStructure " ui-grid="gridOptions" ui-grid-edit>
</div>

I think due to filtering textbox length (textbox css length) this problem is happening.

**Comment by PaulL1** [comment] 2015-05-18 18:19
What version of ui-grid are you using?

When you say width of header, do you mean height of header?  If so, I don't think the length of the filtering box would have any impact on that.

I'm not clear on "filtering part coming" v's "filtering part not coming" and what that means.  Does that mean the header height is adjusting correctly when "filtering part not coming"?

**Comment by debayan31** [comment] 2015-05-19 13:40
I am using "ui-grid-unstable.js" with version "ui-grid - v3.0.0-rc.20-b2fdba9 - 2015-03-22".

I mean to say when I am using "ui-grid-edit and ui-grid-selection" then only issue is coming.

But the header height is adjusting correctly when I am not using "ui-grid-selection" property.

**Comment by PaulL1** [comment] 2015-05-19 18:21
OK, I wonder if this is another flavour of the header height issues.  Have you tried upgrading to latest unstable, which has some header height fixes?

**Comment by debayan31** [comment] 2015-05-22 07:23
I had tested this with latest version , height adjusing issue is not there but in this version has a another issue :

When 'Filtering condition is true' is on, 'scroll down data grid' to some extent, and then try to select any row then highlighted row and selection not aligned.

kindly find screenshot for details.

![screenshot](https://cloud.githubusercontent.com/assets/11749797/7765916/51da0e4e-0081-11e5-8419-2e9517adc731.jpg)

**Comment by debayan31** [comment] 2015-05-22 09:48
Another issue observed:
Download All Data As Pdf is now working.


My Current version is
  ui-grid - v3.0.0-rc.21-11b83eb - 2015-05-21

**Comment by PaulL1** [comment] 2015-05-23 00:09
Duplicate of #3394.  Closing, as I think the original issue is resolved.  If there are new issues, they should really be raised as new items rather than tacking on to a different topic.

**Closed by PaulL1** 2015-05-23 00:09 UTC
Labels: waiting-response
