### ISSUE TITLE
Safari - Moving columns handle has wrong offset when many columns

### ISSUE THREAD

**Issue by Cadrach** [angular-ui/ng-grid#2888] opened 2015-03-03 10:10 UTC
Hi,

On Safari (7.1.3 for me, probably on other versions too), when activating the "move column" feature for tables with many columns, there is an offset on the handle when moving the column. Please note that the more you scroll on the right to some columns not seen initially, the larger the offset seems to be.

Plunker with the issue: http://plnkr.co/edit/e984mLFqa9o8XZqnGXEm?p=preview

Happens on v3.0.0-rc.20-0b29072 for me

**Comment by Cadrach** [comment] 2015-03-03 11:09
I think I found the issue, it looks like getBoundingClientRect does not work correctly when there is a scroll in the container. I have applied the following correction successfully:
https://github.com/Cadrach/ng-grid/commit/f6fbf3b4856500ebf4c93a77854d99b4468a2875

Do you want me to create a pull request? (Never done it before so was not sure it was the right thing to do)

**Comment by Cadrach** [comment] 2015-03-03 13:00
I think I found the issue, it looks like getBoundingClientRect does not work correctly when there is a scroll in the container. I have applied the following correction successfully:
https://github.com/angular-ui/ng-grid/compare/master...Cadrach:master

Do you want me to create a pull request? (Never done it before so was not sure it was the right thing to do)

**Comment by PaulL1** [comment] 2015-03-03 14:53
I'm not familiar with the code itself in this area (@jpuri may help), but if it is a valid fix then yes a PR would be appreciated.  Take a look at the first timers guide if you're not sure how to do it.

We had a similar sounding problem with column menu which turned out to be related to a change in the way we rendered the header, and column virtualisation.  When columns are no longer rendered (as they scroll offscreen) we add to the parent offsetLeft to make spare space, and columnMenu wasn't including this.  It could be the cause of this?  Refer #2871

**Comment by Cadrach** [comment] 2015-03-03 15:05
Ok, it looks to be the same kind of issue, but mine is happening only on Safari, Chrome looks to be working fine so maybe it is a behavior specific to Safari for **getBoundingClientRect**

I will create a pull request and let you guys see if you want to merge it, it is only 4 lines that apply only in Safari.

**Comment by c0bra** [comment] 2015-03-03 15:08
Is this an actual bug within Safari? If so, can we find or file a bug report? And do we know if any other Apple-type browsers or devices are affected?

**Comment by Cadrach** [comment] 2015-03-03 15:16
There is not much around for this bug, as far as I can tell there seems to be an issue in iOS8 with getBoundingClientRect, but for me the bug happens on Safari Mac and there is not much about a bug with the function on the classic OS. 
The bug did not happen on Safari PC (PC & MAC versions are quite different anyways) but since the new way to compute is correct it keeps working correctly, it just does not use getBoundingClientRect.

**Comment by PaulL1** [comment] 2015-03-09 06:30
@c0bra: could this progress to merging?

**Comment by PaulL1** [comment] 2015-03-28 21:52
Merged, closing.

**Closed by PaulL1** 2015-03-28 21:52 UTC
Labels: bug
