### ISSUE TITLE
Not working with angular 1.4

### ISSUE THREAD

**Issue by aaronucsd** [angular-ui/ng-grid#3757] opened 2015-06-11 17:00 UTC
I have angular 1.4 version and it's not working with the ui-grid. I thought 1.3+ should work?

**Comment by JLLeitschuh** [comment] 2015-06-11 17:58
Known issue: #3658
The grid has been tested with Angular 1.2.\* and 1.3.\*. However, 1.4.\* is a new release. Major version bumps usually happen because of a breaking change.

**Comment by aaronucsd** [comment] 2015-06-11 18:01
I see. Buy even when I fall back on 1.3. And then reinstall angualr-ui-grid I get the menu to find suitable version of angular to work with ui-grid. And it trying to resolve to 1.2.16.

**Comment by kcaron-cst** [comment] 2015-06-11 19:25
I am using RC21 with ng 1.4. Just fine so far, just just started with this project. Only using `ui-grid-selection` as far as extra directives go at the moment.

**Comment by c0bra** [comment] 2015-06-11 21:57
Yep there's some issues; hope to fix very soon.

Closing as a dupe of #3658

**Comment by aaronucsd** [comment] 2015-06-11 21:58
Cool. Can't wait. Thanks!

**Closed** 2015-06-11 21:58 UTC
Labels: duplicate
