### ISSUE TITLE
UI Grid Alignment issue in IE version 9.0

### ISSUE THREAD

**Issue by ArunMNew** [angular-ui/ng-grid#3884] opened 2015-06-29 10:48 UTC
Hi All

We are facing one browser compatibility issue(alignment issue) in UI Grid at IE version 9.0

The problem is that there is an alignment gap between column header border and cell content border.
But this is working fine in other browsers like Google chrome, Mozilla, Opera...

Please see the screenshot below for the reference. It is an urgent issue and we need fix ASAP.
Please reply if anyone knows how to fix this issue.

![ui_grid_ie_9_alignment_issue](https://cloud.githubusercontent.com/assets/12839746/8406404/8d7d684a-1e79-11e5-91ab-dd0fc7a29bf6.png)

**Comment by c0bra** [comment] 2015-06-29 14:39
Closing as duplicate of #3854.

**Closed by c0bra** 2015-06-29 14:39 UTC
Labels: Browser IE, duplicate

**Comment by ArunMNew** [comment] 2015-07-01 11:49
Hi c0bra,

Any update on this issue please ?

**Comment by JLLeitschuh** [comment] 2015-07-01 14:33
Please direct questions at this issue to the open version #3854
