### ISSUE TITLE
Change cell template of a grid onclick of button or on any other event.

### ISSUE THREAD

**Issue by aksharak** [angular-ui/ng-grid#3005] opened 2015-03-13 11:37 UTC
Is there a possibility that i can change the celltemplate on click of a button outside the grid or any other event such as row click or anything.

**Comment by c0bra** [comment] 2015-03-13 14:52
You could do this inside a cellTemplate with `ng-show` or `ng-if`. You cannot swap out cellTemplates on demand.

**Comment by aksharak** [comment] 2015-03-16 04:28
Hi, The problem am facing is i have 2 grids where on click of a row in Grid 1, all the values are populated in Grid 2. Now i change the value in editable textbox in Grid 2, the background color of the textbox changes to red. Now i click on save button on top will make the textbox back to normal. Now instead of save button if i click on the next row in Grid 1, the values are populated in the Grid 2, but the textbox color is retained. How to make the color back to normal even on click of next row in Grid 1? 
Here is the Plunker: http://embed.plnkr.co/WUg173JQYXceTrsTu7kD/preview

**Comment by PaulL1** [comment] 2015-03-16 05:19
Is this not a duplicate of #2990?

**Closed by PaulL1** 2015-03-16 05:19 UTC
