### ISSUE TITLE
ui-grid rowSelectionChanged event calling twice in touch devices not in browser

### ISSUE THREAD

**Issue by srinivasarao549** [angular-ui/ng-grid#2842] opened 2015-02-25 13:53 UTC
Hi All,

Any help this will be greatly appreciated and thanks in advance.

I am facing the problem with latest version of ui-grid(3.0.0-RC.18-7774d30) .  rowSelectionChanged event firing twice because of this reason i am not able to select the row. It is weirdly happening only in touch devices not in browser. 

I checked the selection example in ui-grid site on my ipad it is also working same rowSelectionChanged event fired twice.

Observation : In line no :5307 in ui-grid.js rootscpe.on event firing twice.

**Comment by cookednoodles** [comment] 2015-02-25 14:27
This is https://github.com/angular-ui/ng-grid/issues/2838

**Comment by c0bra** [comment] 2015-02-25 15:51
Closing as duplicate of #2838.

**Closed by c0bra** 2015-02-25 15:51 UTC
Labels: duplicate
