### ISSUE TITLE
less sources in bower repository

### ISSUE THREAD

**Issue by WebDevCodr** [angular-ui/ng-grid#2216] opened 2014-11-24 17:36 UTC
Would be great to have less files in bower repository.
This offers the ability to import the main.less file within own less files to overwrite variables like @font-path. This is much easier then rewrite url() in compiled css files. 

This pattern works great with projects like FontAwesome or TwitterBootstrap.

**Comment by c0bra** [comment] 2015-04-16 21:25
#2778 is a duplicate of this, but I'm leaving that one open as it has more discussion.

**Closed by c0bra** 2015-04-16 21:25 UTC
Labels: build
