### ISSUE TITLE
Expandable scrolling is broken. Is there a way around?

### ISSUE THREAD

**Issue by agzam** [angular-ui/ng-grid#3473] opened 2015-05-11 20:44 UTC
Scrolling is broken for expandables. 
when you scroll, row headers don't move. 
this is what I mean: http://g.recordit.co/SD5AZ1BSWb.gif
Is there a way around this thing? I need to make it work rather sooner.
here's [jsbin](http://jsbin.com/cayiyiyuga/3/edit?js,output)

thanks in advance.
ps.: also when you scroll all expanded rows up, there's no way to scroll them back towards the bottom - mouse seem to be not responding.

**Comment by PaulL1** [comment] 2015-05-16 04:46
It doesn't seem to do that in the tutorial, so I'm assuming it's something different in your code.  Are you also getting the problem in the tutorial, or only in your code?

I can't really see anything in your code that would cause it though.  Could you work the other way, starting with a tutorial and building up until you have something near your code, and see what it is that causes the issue?

**Comment by agzam** [comment] 2015-05-18 18:49
Well I couldn't reproduce the same behavior using these grids http://ui-grid.info/docs/#/tutorial/216_expandable_grid, there's another issue that seems to be affecting expandable grids with too many rows. Try for example clicking 'Expand All' and scroll all the way to the bottom. It doesn't re-render grid's canvas at all.

**Comment by c0bra** [comment] 2015-06-19 18:02
Closing as a duplicate of #2759

**Closed by c0bra** 2015-06-19 18:02 UTC
Labels: waiting-response
