### ISSUE TITLE
Not correctly show column footer after async load option

### ISSUE THREAD

**Issue by GoldyMark** [angular-ui/ng-grid#2686] opened 2015-02-01 08:15 UTC
When I first time load data,the column footer showed correctly.

After that I loaded data from server,the column footer became narrow.

It might be css style problem?

plunker here:http://plnkr.co/edit/IpGd7R
--

**Comment by GoldyMark** [comment] 2015-02-01 13:59
**Before async load:**
![qq20150201-1](https://cloud.githubusercontent.com/assets/8085682/5992283/730bc582-aa5d-11e4-83f1-25103c33a547.png)

**After async load:**
![qq20150201-2](https://cloud.githubusercontent.com/assets/8085682/5992284/7320236a-aa5d-11e4-8c19-fd5904850d91.png)

**Comment by PaulL1** [comment] 2015-02-02 06:55
@swalters, @c0bra: it looks to me like the change of the columnDefs (with columns of the same name) is resulting in all the columns getting new UIDs.  The header and the body are changing to use the style with the new UID, the footer is still referring to the old styles.

I recall that both of you did some work in this area, @c0bra I think you most recently.

Updated plunker here: http://plnkr.co/edit/VH8fXDZEheLrUx85V5i4?p=preview (I tweaked the css so the header wasn't broken for me, and I changed it to push the new columns rather than replacing the columnDefs).

A hint towards the cause is this change: http://plnkr.co/edit/DkIyIb0GVFYXisnLdMXy?p=preview, in which I give all the columns new names each time, and everything works fine.

**Comment by GoldyMark** [comment] 2015-02-02 10:54
But the column names should not be changed.

After remove numCalls or replace with "",the problem still.

Plunker here:http://plnkr.co/edit/usmnEY
--

**Comment by GoldyMark** [comment] 2015-02-05 01:13
Emm...I did a hack about this problem.

Plunker here:http://plnkr.co/edit/DkhcZD
---

**Comment by c0bra** [comment] 2015-04-16 20:54
I believe this is because when you blow away your column defs the columns are changing their UIDs, which means the CSS class names change. The header was fixed in the last couple months to update their CSS class with a column defs change, but maybe the footer has not been fixed similarly.

I will look into it.

**Closed** 2015-04-16 22:29 UTC
Labels: bug, investigating
