### ISSUE TITLE
Horizontal scrollbar is always scrollable

### ISSUE THREAD

**Issue by wendeldw** [angular-ui/ng-grid#2734] opened 2015-02-09 18:33 UTC
After upgrading to 3.0.0-RC.18.

It seems you can always scroll a small area equivalent to the width of the vertical scrollbar. There is also a double line in the top right corner. Bug is clearly visible in all demos.

Is this a bug or by design. Can it be turned off?

![image](https://cloud.githubusercontent.com/assets/3500036/6112702/66d6a9b8-b092-11e4-9e08-0cd3f39c7727.png)

**Comment by fresnault** [comment] 2015-02-09 18:42
Hello,

You can disable the horizontal scroll bar with enableHorizontalScrollbar option.

$scope.grid = {
    enableHorizontalScrollbar: 0
};

0 -> disable
1 -> enable
2 -> enable when needed

**Comment by wendeldw** [comment] 2015-02-09 18:48
Thanks for the response, but it doesn't fix the bug.

The scrollbar should be visible but without the extra offset.

Something has been changed between RCv12 and RCv18

**Comment by mikila85** [comment] 2015-02-10 07:37
still when the scrollbar is disabled with 0, it doesnt show but when pressing middle mouse and scrolling right you can still reach the dead zone:

![untitled](https://cloud.githubusercontent.com/assets/3965957/6123262/728369b0-b108-11e4-9ca0-6269e7635177.png)

**Comment by wendeldw** [comment] 2015-02-10 08:41
You can see the double lines in the area marked as green.

Regardless, I need to have the scroll-y enabled, as I did in rc12. There is
an offset which appeared after version rc12.

Paul, can you comment on this?


2015-02-10 8:37 GMT+01:00 mikila85 <notifications@github.com>:

**Comment by c0bra** [comment] 2015-02-11 02:41
This is a duplicate of #2592

**Comment by mszpiler** [comment] 2015-02-13 21:07
I have the same problem :/

**Comment by dczepierga** [comment] 2015-02-16 08:43
I found a place where is bug:
https://github.com/angular-ui/ng-grid/blob/master/src/js/core/directives/ui-grid-header.js#L75

In this place the scrollbar width should be substracted from viewport width (viewport include scrollbar width), so it should be changed for something like this:
`var availableWidth = containerCtrl.colContainer.getViewportWidth() - grid.scrollbarWidth;`

`grid.scrollbarWidth` is greater than `0` only when `enableVerticalScrollbar` is set to `ALWAYS`, so it should work when we have scroll enabled and disabled...

I don't know this library, so it's hard for me to say that will break something else or not - i think no, but maybe someone else confirm this or propose how do this better?

**Comment by c0bra** [comment] 2015-02-16 17:37
Closed via cf86090

**Comment by mikila85** [comment] 2015-02-16 17:40
fixed?? :)

**Comment by dczepierga** [comment] 2015-02-16 17:41
yes fixed :)

**Comment by mikila85** [comment] 2015-02-16 17:42
thank you :+1:   great work!! going to try now.

**Comment by mikila85** [comment] 2015-02-16 17:46
can still drag it with mouse
![image](https://cloud.githubusercontent.com/assets/3965957/6216597/5c7e3710-b614-11e4-9e03-7f3cd45bd1e3.png)
![image](https://cloud.githubusercontent.com/assets/3965957/6216616/7dba085a-b614-11e4-9407-870d37406ccf.png)

**Comment by dczepierga** [comment] 2015-02-16 18:09
@mikila85, but the version e099c5b5721afcae40d1ad3cc2c8b4e5bde00731 is before this fix?

Look here:
https://github.com/angular-ui/ng-grid/commits/master

You should have at least cf86090f66ee057f541961d563ca42597112bdb4

**Comment by mikila85** [comment] 2015-02-16 18:13
thank you, sorry, still new at this i'll learn, 
thank you again :)

**Comment by mszpiler** [comment] 2015-02-16 23:20
I checked it. It is almost perfect, but when enableHorizontalScrollbar = 2 scrollbar shouldn't be visible but it is visible.

**Comment by c0bra** [comment] 2015-02-17 00:06
OK thanks for checking that. I'll try again tomorrow :)

**Comment by dczepierga** [comment] 2015-02-17 06:23
@mszpiler, scroll is always visible because options `enableHorizontalScrollbar = 2` is not supported? :)

Look here for available values for scrollbar:
https://github.com/angular-ui/ng-grid/blob/master/src/js/core/constants.js#L104

And here for relese notes:
> scrollbars.WHEN_NEEDED no longer an option

So it not works because this option is not supported ;)

**Comment by mikila85** [comment] 2015-02-17 07:11
@mszpiler how did you get the version that includes the fix? 
all i find here: https://github.com/angular-ui/ui-grid.info/tree/gh-pages/release
is   * ui-grid - v3.0.0-rc.19-78a4b43 - 2015-02-16
and i dont see the fix is there

**Comment by mszpiler** [comment] 2015-02-17 07:36
@mikila85 I build it with changes @c0bra on master
@dczepierga thank you for detailed explanation - so solution for me is ok :)

**Comment by mikila85** [comment] 2015-02-17 07:37
how did you build it? (sorry for noob question)

**Comment by mszpiler** [comment] 2015-02-17 07:43
Follow with instruction on https://github.com/angular-ui/ng-grid

**Comment by mikila85** [comment] 2015-02-17 08:23
thank you! :)

**Comment by mikila85** [comment] 2015-02-17 08:42
stuck like this for a very long time :(
![image](https://cloud.githubusercontent.com/assets/3965957/6225363/afe017b6-b691-11e4-8210-31a9313f72f5.png)

**Comment by mikila85** [comment] 2015-02-17 09:04
still hasnt finished lol. something is wrong

**Comment by c0bra** [comment] 2015-02-17 14:57
OK sounds like this issue is indeed fixed, then. Closing again.

**Closed by c0bra** 2015-02-17 14:57 UTC
Labels: bug, duplicate

**Comment by dilumich** [comment] 2015-07-27 22:26
I am using ng-grid and I cannot switch to ui-grid since my app is heavily depends on ng-grid. Is it possible to fix this issue for ng-grid.

**Comment by pradapkumar** [comment] 2016-09-23 17:13
I have the same issue and there is no misalignment when I go to that page through navigation menus but when I click refresh and when the grid loads I am getting the misalignment. 
On the first navigation load I see a small rectangle bar in the top of the vertical bar but when I refresh it goes off and get this issue. as in the above first screenshot in this thread the rectangle box above the scroll is going off when I refresh.
 I there any fix for this? I tried all the option that is showed nothing is working
Please help to fix this
