### ISSUE TITLE
Vertical scrolling freakishly fast (probably emulated)

### ISSUE THREAD

**Issue by Thinkscape** [angular-ui/ng-grid#937] opened 2014-01-22 21:02 UTC
I went here: http://ui-grid.info/customizer/

MacOS, latest Chrome.

When I try to scroll the sample grid on the right, scrolling a pixel down causes the grid to scroll like 3 rows. Scrolling down the width of my pointing finger, I've scrolled 3/4 of all the data :-) It's unbearably fast... There's something wrong with how that's calculated. 

Is scrolling emulated in 3.0 ? If it is, quick note - This is bad for so many reasons and I remember other grid components (like in dojo, ext etc.) running away from scroll virtualization. It's especially bad for hardware-accelerated and "elastic" scrolling provided by the OS or the browser. It also ignores OS settings for scroll speed or mouse-specific settings (like logitech software that sometimes gets in the way). It'll also be a problem on mobile devices which heavily optimize how scrolling works and how overflowed elements are rendered.

**Comment by Thinkscape** [comment] 2015-01-27 10:05
@swalters it is not duplicate of #1426

I've just tried latest build `v3.0.0-RC.18-09cb44a` and uigrid is still unusable on mac. A gentle touch on the touchpad scrolls the grid by tens of rows.. it just blinks data. 

Shall I create a separate ticket for this, or do you want to reopen this one?

**Comment by santialbo** [comment] 2015-01-29 12:19
I'm really waiting for this to get fixed since right now it doesn't offer a good user experience on a Mac. As @Thinkscape said, this is not a duplicate of #1426 (@swalters).

Some more information, this is happening when using the trackpad. When I do a very small scroll gesture it scrolls 120px instead of the few pixels it should scroll. Something is wrong in [here](https://github.com/angular-ui/ng-grid/blob/e4b2293a0997adda5c78054592e8bcbbdb65acba/src/js/core/directives/ui-grid-render-container.js#L123) since removing that event handler fixes the issue for me on the examples.

My hardware:
OSX 10.10.1
Chrome 40.0.2214.93 (64-bit)
Firefox 35.0.1

**Comment by swalters** [comment] 2015-01-30 14:37
Chrome on Mac doesn't need the mousewheel events wired.  Without them, it scrolls nicely.  However, Safari won't scroll without the mousewheel events.  What a nightmare.  Research is showing that everyone is struggling with this issue and there doesn't seem to be a definitive answer. 

Volunteers needed for this issue.

**Comment by santialbo** [comment] 2015-02-05 11:40
It might be worth taking a look at how Facebook does it in their Fixed Data Table since it seems to work well in all platforms (examples [here](http://facebook.github.io/fixed-data-table/example-resize.html)). They seem to normalize the scroll [here](https://github.com/facebook/fixed-data-table/blob/403e7884f6515ffe3428016db8c55722db38918b/src/vendor_upstream/dom/normalizeWheel.js).

**Comment by santialbo** [comment] 2015-02-05 11:52
Some more information that might be useful. 
http://stackoverflow.com/questions/5527601/normalizing-mousewheel-speed-across-browsers

**Comment by santialbo** [comment] 2015-02-23 11:22
Aparently this works nicely now. Maybe you can close this issue.

**Comment by PaulL1** [comment] 2015-02-23 16:30
Thanks, closing as requested.

**Closed by PaulL1** 2015-02-23 16:30 UTC
Labels: Hi-Pri Bug
