### ISSUE TITLE
Boolean type Edit by clicking issue on Firefox/Safari

### ISSUE THREAD

**Issue by yuwong** [angular-ui/ng-grid#1785] opened 2014-10-10 15:36 UTC
From the Edit Feature tutorial http://ui-grid.info/docs/#/tutorial/201_editable on Firefox/Safari, the Active column's boolean value is not changeable by clicking. It can only be edited when in focus using the spacebar. The checkbox appears to work fine on Chrome using clicks.

**Comment by PaulL1** [comment] 2015-03-28 09:11
I think the problem is html5 widgets - and the fact that Safari and IE don't implement some of the html5 widget types.  Does that sound correct?

**Comment by PaulL1** [comment] 2015-04-12 07:01
Closing, no further comments for 2 weeks, and no plausible path to a resolution using the vanilla widgets.

**Closed by PaulL1** 2015-04-12 07:01 UTC
Labels: waiting-response

**Comment by yuwong** [comment] 2015-04-13 16:04
Thanks Paul, decided against using the Boolean type altogether now

**Comment by bradlys** [comment] 2016-04-18 23:11
Anyone know how to resolve this? Custom templates or not.

I'm willing to contribute code if anyone knows where the issue lies.
