### ISSUE TITLE
How to format cell number while using grouping SUM, AVG, etc.

### ISSUE THREAD

**Issue by billyaraujo** [angular-ui/ng-grid#3346] opened 2015-04-23 08:35 UTC
Hi,

I have this issue I am trying to format percentages, numbers with a certain n of decimals. I know there is cellTemplate and cellFilter but these convert to string and then grouping SUM, AVG, etc. give null values.  
So how do I format the grouping uiGridGroupingConstants.aggregation values to show n decimal points?

Maybe the ideal would be to have uiGridGroupingConstants.aggregation try to convert values to floats before doing math operations?

**Comment by PaulL1** [comment] 2015-04-23 08:53
Grouping and aggregation work on the underlying element, not on the filtered element.  The standard filters should give no issues with that - I think we use a filter in one of the examples do we not?

**Comment by billyaraujo** [comment] 2015-04-23 10:48
I ended up using cellFilter to do all the formatting. Aggregate values come as string while the column type is float so need special treatment there. However being a string such as "total: 23.3", I don't know the type. Because total can be a float, while count is a integer. 

There is probably a better way to do this.

**Comment by PaulL1** [comment] 2015-04-23 11:00
I do something similar in my code for the group lines - because they get a count put after them in parenthesis.  In my filter I check if there's a count there, if so I unstring it, apply the filter, then put it back together.  It's not ideal, but it works.  Look in #3309 for an example.

I'm thinking about ways to have both the formatted and unformatted versions available for people in their cellTemplates - since it's only on the rowHeaders I can add things to the entities without messing up people's data.  So, if you had a column "account_balance" that you had an aggregation on, I could perhaps put the current content ("total: 1234.56") into the account_balance field, but maybe create $account_balance as well with just "1234.56", and another field $account_balance_agg_type with "total:".  You could then have a cellTemplate that strung this back together (with a filter in the middle) if you are on a row header.  The problem is that this will litter ng-ifs through people's cellTemplates, and that is performance bad.

Another option is for you to drop the headers - I think I put an option in for that.  Then filters work, you just don't get a visual indication of the aggregation type.

**Comment by billyaraujo** [comment] 2015-04-23 11:12
Thank you for your answer.

Is there an option to drop the headers? That would be very useful for me in this case.

It would be nice to be able to access the underlying value and type in groupings, but I guess the performance issues should to be considered.

**Comment by PaulL1** [comment] 2015-04-23 20:03
`groupingSuppressAggregationText`, documented on http://ui-grid.info/docs/#/tutorial/209_grouping

**Comment by PaulL1** [comment] 2015-05-25 23:57
This looks resolved: closing.  I note that the new grouping implementation, which will come in rc22, changes a lot of this, and gives the underlying value, type and label to the templates, and provides for custom finalizers, which gives an easy way to access the values.

**Closed by PaulL1** 2015-05-25 23:57 UTC
Labels: waiting-response
