### ISSUE TITLE
Add option in columnDefs to avoid adding aggregation menu items if grouping is enabled

### ISSUE THREAD

**Issue by Curioasa** [angular-ui/ng-grid#3557] opened 2015-05-21 20:32 UTC
I have recently struggled with decorating around this issue and, with help, came up with a functional, yet hard to extend solution, that can be seen in the following plunker: http://plnkr.co/edit/WuCceTIhavdgVTYuer8R?p=preview

Basically, what I needed was a way for the user to enable grouping through the menu on each column without displaying the 5 aggregation menu items, because they do not make sense in my functional specs.

Thus, I think it would be nice if the menu items would be more configurable through the grid options.

**Comment by PaulL1** [comment] 2015-05-21 21:18
Duplicate of #3379.  And was merged this morning.

**Closed by PaulL1** 2015-05-21 21:18 UTC
Labels: duplicate
