### ISSUE TITLE
Disable Row

### ISSUE THREAD

**Issue by lecoleco** [angular-ui/ng-grid#3071] opened 2015-03-20 14:04 UTC
Hi,

I want to disable a row until the promise return.

I try this.

$scope.gridApi.selection.clearSelectedRows();
$scope.gridOptions.enableRowSelection = !$scope.gridOptions.enableRowSelection;
$scope.gridApi.core.notifyDataChange( uiGridConstants.dataChange.OPTIONS);

The row selected comes unSelect but the disable not work,.

Thanks

**Comment by PaulL1** [comment] 2015-03-20 20:48
I did a plunker to demonstrate it, but it now won't save.  I think the key here is that enableRowSelection deals only with clicking in the body of the grid, not with selecting by the rowHeader.  So if you turn off `enableRowSelection` the expected result is that clicking in the body of the grid won't select the row, which means you have to have first turned off `enableRowHeaderSelection`.

The code was:
```
var app = angular.module('app', ['ngTouch', 'ui.grid', 'ui.grid.selection']);

app.controller('MainCtrl', ['$scope', '$http', '$log', '$timeout', 'uiGridConstants', function ($scope, $http, $log, $timeout, uiGridConstants) {
  $scope.gridOptions = { 
    enableRowHeaderSelection: true,
    enableRowSelection: true,
    enableSelectAll: true,
    selectionRowHeaderWidth: 35,
    rowHeight: 35,
    showGridFooter:true
  };

  $scope.gridOptions.columnDefs = [
    { name: 'id' },
    { name: 'name'},
    { name: 'age', displayName: 'Age (not focusable)', allowCellFocus : false },
    { name: 'address.city' }
  ];


  $http.get('https://cdn.rawgit.com/angular-ui/ui-grid.info/gh-pages/data/500_complex.json')
    .success(function(data) {
      $scope.gridOptions.data = data;
      $timeout(function() {
        if($scope.gridApi.selection.selectRow){
          $scope.gridApi.selection.selectRow($scope.gridOptions.data[0]);
        }
      });
    });

    $scope.gridOptions.onRegisterApi = function(gridApi){
      //set gridApi on scope
      $scope.gridApi = gridApi;
    };
    
    $scope.disableFirstRow = function() {
      $scope.gridApi.selection.clearSelectedRows();
      $scope.gridOptions.enableRowSelection = !$scope.gridOptions.enableRowSelection;
      $scope.gridApi.core.notifyDataChange( uiGridConstants.dataChange.OPTIONS);      
    };
}]);
```

and

```
<!doctype html>
<html ng-app="app">
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-touch.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.2.26/angular-animate.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/csv.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/pdfmake.js"></script>
    <script src="http://ui-grid.info/docs/grunt-scripts/vfs_fonts.js"></script>
    <script src="http://ui-grid.info/release/ui-grid-unstable.js"></script>
    <link rel="stylesheet" href="http://ui-grid.info/release/ui-grid-unstable.css" type="text/css">
    <link rel="stylesheet" href="main.css" type="text/css">
  </head>
  <body>

<div ng-controller="MainCtrl">
  <button ng-click="disableFirstRow()">Disable First Row</button>
  <div ui-grid="gridOptions" ui-grid-selection class="grid"></div>
</div>

    <script src="app.js"></script>
  </body>
</html>
```

**Comment by lecoleco** [comment] 2015-03-22 23:34
Thanks,

I don't know what's the problem, on this plunker work good.

http://plnkr.co/edit/Iu4gbqWno4UrIJi2kVRn?p=preview

But in my application with another plugins not work. 
 :(

**Comment by PaulL1** [comment] 2015-03-22 23:50
OK.  I also don't know what the problem is because I can't see your application, but the usual approach would be to add things to the plunker, making the plunker more and more like your application, until it stops working.

**Comment by lecoleco** [comment] 2015-03-23 11:32
right, I'll tell you when discovering the problem, thank you.

**Comment by PaulL1** [comment] 2015-04-12 06:37
Closing: solution proposed that should resolve the issue, no further comments for 2 weeks, assuming solution has resolved issue.

**Closed by PaulL1** 2015-04-12 06:37 UTC
Labels: waiting-response
