### ISSUE TITLE
Custom filter in headerCellTemplate

### ISSUE THREAD

**Issue by pszawlis** [angular-ui/ng-grid#2886] opened 2015-03-03 07:43 UTC
I created a grid with custom external filter. It works perfectly fine, as long as it is not part of the headerCellTemplate. When it is inside:

1. Data is filtered correctly but the display is not adjusted
2. I didn't manage to apply the same formatting as for Grid Mene, i.e. the drop down overlapping the header and grid cells and not changing header height. 

Please take a look at the Plunker http://plnkr.co/edit/z2Ua5CAypvjSNPb9Psjv?p=preview

**Comment by thomas-koch-comsolit** [comment] 2015-03-05 14:18
this might be a duplicate of #2796

**Comment by pszawlis** [comment] 2015-03-05 19:25
Issue #2796 is a feature request, my case (point 1.) is probably a bug (or hopefully my wrong understanding).

The bottom line is: I was able to create filter using AngularjJs mulit select and it works well as long as it is not part of  headerCellTemplate.

**Comment by PaulL1** [comment] 2015-03-05 20:52
Changes were done on the header height recently that may have fixed point 1.

**Comment by igwejk** [comment] 2015-03-06 08:52
This is a duplicate of [#2731](https://github.com/angular-ui/ng-grid/issues/2731).

@pszawlis see my comment there to understand how you can achieve the behaviour you want.

**Comment by PaulL1** [comment] 2015-04-12 06:55
I think the new filterHeaderTemplate option resolves this: http://ui-grid.info/docs/#/tutorial/306_custom_filters

**Closed by PaulL1** 2015-04-12 06:55 UTC
Labels: waiting-response
