### ISSUE TITLE
Feature Request: SubMenu on column headers

### ISSUE THREAD

**Issue by christrude** [angular-ui/ng-grid#3701] opened 2015-06-05 14:57 UTC
It'd be great, and awfully useful if we had the ability to have 2 levels of menu items available on the column headers. Is there a desire to add this functionality?

The format would look something like this:

    menuItems: [{
        title: 'Outer Scope Alert',
        icon: 'ui-grid-icon-info-circled',
        context: $scope,
        subMenuItems: [{
            title: 'Inner Scope Alert',
            icon: 'ui-grid-icon-info-circled',
            action: function($event) {
                this.context.blargh(); 
            },
            context: $scope
        }
    }]

**Comment by PaulL1** [comment] 2015-06-05 20:42
Duplicate of #3433

**Closed by PaulL1** 2015-06-05 20:42 UTC

**Comment by christrude** [comment] 2015-06-05 20:48
Thanks, I couldnt find the other

**Comment by ajentering** [comment] 2017-05-14 07:20
Hi @PaulL1 i am trying to impliment the same in my project but cant see the subMenuItems.
below is my code:
var app = angular.module('app', ['ngAnimate', 'ngTouch', 'ui.grid']);
 
app.controller('MainCtrl', ['$scope', '$http', 'uiGridConstants', function ($scope, $http, uiGridConstants) {
  $scope.blargh = function() {
    alert("I'm in the outer scope!");
  };
 system = $scope;
  $scope.gridOptions = {
    enableSorting: true,
    columnDefs: [
      { field: 'name', enableColumnMenu: false },
      { field: 'gender', enableHiding: false, suppressRemoveSort: true, sort: { direction: uiGridConstants.ASC } },
      {
        field: 'company',
//        menuItems: [
//          {
//            title: 'Outer Scope Alert',
//            icon: 'ui-grid-icon-info-circled',
//            action: function($event) {
//              this.context.blargh(); // $scope.blargh() would work too, this is just an example
//            },
//            context: $scope
//          },
//          {
//            title: 'Grid ID',
//            action: function() {
//              alert('Grid ID: ' + this.grid.id);
//            }
//          },
//          {
//            title: 'Column Title Alert',
//            shown: function () {
//              return this.context.col.displayName === 'Company';
//            },
//            action: function() {
//              alert(this.context.col.displayName);
//            }
//          }
//        ]
        
        
        menuItems: [{
            title: 'Outer Scope Alert',
            icon: 'ui-grid-icon-info-circled',
            action: function($event) {
              this.context.blargh(); // $scope.blargh() would work too, this is just an example
            },
            context: $scope,
            subMenuItems: [{
            	
                  title: 'Grid ID',
                icon: 'ui-grid-icon-info-circled',
                action: function($event) {
                	 alert('Grid ID: ' + this.grid.id);
                },
                context: $scope
            }
        ]
        
      }]
      }
    ]
  };
  $scope.myData = [
                   {
                       "name": "Cox",
                       "gender": "female",
                       "company": "xyz"},
                       {
                           "name": "Cox",
                           "gender": "male",
                           "company": "xyz"},
                           {
                               "name": "Cox",
                               "gender": "male",
                               "company": "xyz"},
                               {
                                   "name": "Cox",
                                   "gender": "female",
                                   "company": "xyz"}
                   ]
  $scope.gridOptions.data = $scope.myData;

}]);

below is the image for my code:
![image](https://cloud.githubusercontent.com/assets/28683141/26031947/78620a56-38a3-11e7-8ec0-846d81eb756b.png)

I am trying to impliment below grid with custom filter menu:

![image](https://cloud.githubusercontent.com/assets/28683141/26031964/d8b1bff0-38a3-11e7-8daa-478453d22e32.png)
