### ISSUE TITLE
Selection tutorial is broken after last commit

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/ng-grid#3166] opened 2015-03-31 00:32 UTC
Selection tutorial is missing the selection header and checkboxes.

**Comment by PaulL1** [comment] 2015-03-31 01:15
Duplicate of #3165.  The issue is that the fonts are broken.  This looks to be a build process issue, the same code built locally works fine.

**Closed by PaulL1** 2015-03-31 01:15 UTC
Labels: duplicate
