### ISSUE TITLE
Horizontal scrollbar positioning

### ISSUE THREAD

**Issue by Dev63** [angular-ui/ng-grid#2407] opened 2014-12-21 03:45 UTC
As of today (Dec-20) the latest unstable version leaves a gap between the bottom scrollbar and the footer.

![image](https://cloud.githubusercontent.com/assets/9340860/5517088/4e562cf4-8880-11e4-9203-e5025e93d18e.png)

I am seeing this on both IE and Chrome on Windows.

**Comment by PaulL1** [comment] 2015-01-14 20:39
Is this still happening, or have recent changes sorted it out?

**Comment by Dev63** [comment] 2015-01-14 22:47
This area is stlll having problems, but behaving differently.  Look at the horizontal scroll bar for the [Footer Tutorial](http://ui-grid.info/docs/#/tutorial/105_footer): 

* Every table now shows an active horizontal scrollbar whereas before that was not true.  I think something is incorrectly calculating the width of the table.  

* Worse, the scrollbar is appearing above the footer row (in my own tables, the footer row isn't appearing at all any more (perhaps overflowing out of bounds in my case)).

**Comment by PaulL1** [comment] 2015-01-14 23:32
@swalters: I think some of this is now expected behaviour?

**Comment by swalters** [comment] 2015-01-15 02:58
Yep, we had to make some compromises to get the horizontal scrollbar in the viewport.  The viewport is above the column footer.

**Comment by Dev63** [comment] 2015-01-15 04:52
@swalters I really like ui-grid, but the grid has to function AND look good for it to be used. FWIW, I've been using a build from Dec-19 instead, and it seems to work great and look nice.  I'm not sure what had to change, and I wonder if the tradeoff is worth it...

Anyway, with the latest, the footer row doesn't even show up in my app.  I suspect it has something to do with living in a flex-grow div, but ... no footer at all.  Here's a link to [an existing plunker](http://plnkr.co/edit/uUUuiBZF7xQiHCgTSG8R?p=preview) from an old (low priority) issue that illustrates the missing footer.  It also shows that the grid has problems drawing itself when there's a hidden div above it in the page, but that's of minor consequence, and if you just remove the hidden div from the HTML, you'll see that the footer is still missing.

**Comment by jcompagner** [comment] 2015-01-15 08:29
i see in the demo's that the own scrollbars that we had are now not used anymore?
its not purely a viewport that has overflow:scrolll by itself?

I guess thats why we see suddenly a bit more scrolbars (especially the horizontal one because the vertical makes the horizontal because the vertical takes up space)

are we going to fully remove the native scrollbar directives and stuff (i see that they are currently still in the dom as a not rendered div)

Is this new viewport overflow:scroll taken into account the scrollbars property? So that if i really never want to see a horizontal one it will not show up?
(i guess its now by default in "when_needed" instead of what we had "always")

**Comment by Dev63** [comment] 2015-01-15 22:16
@swalters OK ... I discovered that my footers don't show up any more because I didn't notice the options change, and that we now need to use 'showColumnFooter: true' rather than `showFooter`.  My mistake!

And while I personally don't like the horizontal scrollbar above the footer, I understand that's a decision that has been made.  

The only thing that still seems "wrong" to me is that the horizontal scrollbar allows me to scroll the table even when there shouldn't be anything to scroll.  It adds a bit of unused table space at the right.
All the Tutorials show this, now, so I suppose this is also intended behavior?  I'm just a big fan of keeping UI clean and not distracting users with things that are irrelevant, so the addition of live scrollbars when they're not wanted or needed is strongly undesirable.  But if intended, I think this whole bug chain can now be closed.  If so, is there any way to override this behavior?

**Comment by Dev63** [comment] 2015-01-19 01:12
@PaulL1 There have been some further comments in this chain, including by @jcompagner, who reveals that the unwanted horizontal scrollbar is appearing because the vertical scrollbar is taking up uncalculated space (so there's no way to have a table without a movable horizontal scrollbar with which you can shuffle the table a quarter of an inch).  Is this something that will get addressed ( I hope! )?

**Comment by c0bra** [comment] 2015-04-14 14:03
Closing as this issue appears to be gone; I can't reproduce it.

**Closed by c0bra** 2015-04-14 14:03 UTC
Labels: bug
