### ISSUE TITLE
Scrolling to the right end results in shift between header and body

### ISSUE THREAD

**Issue by AnneLaureF** [angular-ui/ng-grid#2521] opened 2015-01-09 10:08 UTC
When reaching the right end of the grid the header columns and the data columns are not properly aligned. See for example on the homepage:
![image](https://cloud.githubusercontent.com/assets/497836/5678118/47c4377c-97ef-11e4-9e9e-730eab3e717f.png)
I suspect this example shouldn't scroll (and the one below definitely shouldn't).

It seems the header row and the grid have the same canvas width and the same viewport width but the grid has the vertical scrollbar.

It doesn't happen in commit d9b2314fca4d34e4a276d44bbc2d00e9a76d558a so it's been introduced after that. Maybe the scrollbar width was added to the grid canvas width somewhere and it should have been removed when changing the way scroll works ?

**Comment by PaulL1** [comment] 2015-01-10 20:55
There were some substantial changes went into scrolling yesterday, which should have fixed some of these issues (or perhaps they newly created this?).  Could you perhaps check again?

**Comment by axelstudios** [comment] 2015-01-11 04:51
This still exists, and was introduced with the 30df7d4af08d9151cdb1c39bf15a76b44a77ab2e merge, which also appears to have broken both `enableHorizontalScrollbar: uiGridConstants.scrollbars.NEVER` and `enableVerticalScrollbar: uiGridConstants.scrollbars.NEVER`.

Similarly, the vertical row selection header is now misaligned when you scroll all the way to the bottom.

http://plnkr.co/edit/juFzMptmHdOLky9jlPzU?p=preview

**Comment by AnneLaureF** [comment] 2015-01-12 07:43
Just confirming the issue is still present in 97dbff87d3a25e24578eec5f16214a894ec4b9a8

**Comment by herdanskecommodities** [comment] 2015-01-29 20:31
I am still seeing this with the latest unstable.

**Comment by kencaron** [comment] 2015-02-04 00:15
@axelstudios I'm not positive this was introduced with 30df7d4 (Jan 8) if only because I'm still on RC18 (Dec 9) and I'm noticing this same misalignment. Possibly there are multiple causes of the issue. 

In my case it would only appear when the user horizontally scrolled the grid due to large datasets. My misalignment was solved when I assigned a class with a width to my `ui-grid` element.

**Comment by axelstudios** [comment] 2015-02-05 16:06
For me, this bug is gone with the latest unstable.

**Comment by c0bra** [comment] 2015-02-16 16:51
This bug still exists for me with latest unstable and rc19.

**Comment by c0bra** [comment] 2015-02-16 16:53
@kencaron Can't have been 30df7d4; the only changes there are syntax and whitespace alterations for a merge commit.

**Comment by sachinny21** [comment] 2015-02-17 19:26
So a fix was made to align the column lines with the header lines but in the process a gap was introduced at the beginning of the grid...

![alignmentnewerror](https://cloud.githubusercontent.com/assets/9724198/6235513/f80305f2-b6b0-11e4-9f0e-db003479d590.png)

**Comment by c0bra** [comment] 2015-02-19 15:09
@sachinny21 OK I'll take a look

**Comment by sachinny21** [comment] 2015-02-19 15:24
thanks cobra!

**Comment by kencaron** [comment] 2015-02-27 18:01
Not sure how helpful this is as I can't reliably reproduce this. Started removing columns when the width of the grid was wider than the containing div.

`RC20 in Firefox 35 on OS X 10.10.2`

![](http://f.cl.ly/items/3N2U3j1m42353V0n0H2i/Screen%20Shot%202015-02-27%20at%2010.47.39%20AM.png)

**Comment by c0bra** [comment] 2015-03-11 21:18
@sachinny21 I'm not seeing this behavior on my test grid:

![no_gap_grid](https://cloud.githubusercontent.com/assets/105007/6607096/3a1e7470-c80a-11e4-87e9-cc4a2997b874.png)

Can you double-check it?

**Comment by morungos** [comment] 2015-03-18 18:02
I'm still seeing something like this in 1fdcf3d1c in current master, although the behaviour for me is different. I have a lot of columns, and as I scroll, periodically entire headers vanish and leave with fewer headers than columns. Not sure if this is identical in cause: I'll see if I can pin down the commit as it wasn't there in rc16.

**Comment by morungos** [comment] 2015-03-18 19:03
Okay, the issue I've seen is in 893bb13 (fix(uiGridHeader): Fix dynamic header heights), and therefore it isn't the same. Taking a wild guess, it's the lines which take away the min-height constraint on header cells allowing them to collapse away entirely when there are too many to fit. I'll try to build a small example to demonstrate.

**Comment by c0bra** [comment] 2015-03-30 16:08
@morungos Any luck on making that example? Can you tell me if you're having issues in a particular browser. I know that table-based CSS can be a bit wonky between different browsers and versions.

**Comment by morungos** [comment] 2015-03-31 18:08
@c0bra Sadly no -- my app is in healthcare, so I just didn't get time to remove all the bits I needed to, and there were too many weird requests from my users to sustain with the current status of ui-grid, so I've switched for now to handsontable for now, which isn't as clean an API but does seem to handle the basic UI/scrolling/editing well, if without the scalability I'll need some day.

**Comment by c0bra** [comment] 2015-03-31 22:07
Ah, I understand. Thanks for the info on this issue, though. I'll look into the column collapsing thing.

**Comment by c0bra** [comment] 2015-04-13 20:40
Since there have been so many changes to scrolling recently I'm going to close this as the only thing left was a difficult-to-repro column collapsing issue. If it's still a problem after the scrolling changes I trust it will be filed again.

**Closed** 2015-04-13 20:40 UTC

**Comment by kcaron-cst** [comment] 2015-04-13 22:04
I thought this was completely gone until I received screenshots of this on IE9. Really can't blame anyone for not wanting to deal w/ that browser though.

**Comment by jtpolizzi** [comment] 2015-06-01 17:14
I'm having this exact issue in IE9.  It is the same in 20 and 21.

It seems to work fine when only a few columns are displayed - but has problems when there are more and it has to scroll

**Comment by bernhard-hofmann** [comment] 2015-07-15 09:25
I see the issue in IE9 when I set the column width narrower than the text of the heading will allow. Chrome is fine with the `text-overflow:ellipsis` but IE9 (which [technically supports this overflow](http://caniuse.com/#feat=text-overflow)) doesn't show the text with ellipses and (I'm guessing) therefore pushes the column heading width out which then doesn't align with the data column.

**Comment by kencaron** [comment] 2015-07-15 13:51
@bernhard-hofmann after re-reading @c0bra's comment, it might be necessary to open a new issue for this IE9 issue to be considered. Not sure the policy on reopening closed issues.

**Comment by nitoloz** [comment] 2015-10-21 12:49
Reproduced with 3.0.7
![scroll](https://cloud.githubusercontent.com/assets/7154361/10636916/f8ba94f6-7802-11e5-8831-928aed25d09d.png)

**Comment by amex132** [comment] 2015-12-18 21:00
We have a requirement that some of our webapps allow a reasonable amount of zoom in and zoom out say like from 80% to 150% in a browser window. We're seeing this behavior on browser zoom in/out. 

Meaning alignment between column header and body gets worse towards the right end.

I believe we're also using 3.0.7.

**Comment by gabrieldocarmosantana** [comment] 2016-04-20 14:57
I had the same issue in IE9 and  i Solve Setting the same width of the title like width the collum.

If the width of the collum was less than width of the size of the title the problem occours in ie9.

**Comment by Galaba563** [comment] 2016-08-25 09:17
Still i am facing the issue

**Comment by pradapkumar** [comment] 2016-08-25 17:09
I have the same issue, I have the latest release 3.2.6
 can any one suggest how to fix this Header and data misalignment?

**Comment by gabrieldocarmosantana** [comment] 2016-08-25 19:27
The width of your collum has to have the size of your title. If your value is lowwer the problem occours. 
 {
                  field: "TipoSolicitacao",
                    name: "Tp. Solicit",
                    width: "10%"
                },
                {
                    field: "Documento",
                    name: "Documento",
                    width: "15%"
                },

**Comment by antonio91kim** [comment] 2016-12-16 08:31
Hope everyone can solve this problem with this tip.
my idea is making an empty box beside last column header.
Assume that scroll width is 20px.
And add below lines on style sheet.
```
.ui-grid-header-cell.include-scrollbar:last-child .ui-grid-cell-contents {
  margin-right: -20px;
  padding-right: 20px;
}
```

**Comment by deepaksm1** [comment] 2017-03-14 06:18
Same issue I faced in Kendo Grid, solved using this trick:- http://www.letmeknows.com/2017/03/07/header-and-column-data-mis-aligned-after-implementing-in-kendo-grid
