### ISSUE TITLE
Filter boxes do not show 'close' buttons any longer after last commit

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/ng-grid#3168] opened 2015-03-31 00:38 UTC
Check out any tutorial that has filter boxes. Enter text. No 'close' buttons are visible any longer.

**Comment by PaulL1** [comment] 2015-03-31 01:16
Duplicate of #3165.  The issue is that the fonts are broken.  This looks to be a build process issue, the same code built locally works fine.

**Closed by PaulL1** 2015-03-31 01:16 UTC
Labels: duplicate
