### ISSUE TITLE
TAB key does not work properly within a editableCellTemplate

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ng-grid#2966] opened 2015-03-10 14:24 UTC
Hi,

With default editing functionality, TAB key is working great while cellNav service is injected to the grid. But as you can see from the below plunk, TAB key is not working as expected while using editableCellTemplates.

Plunk: http://plnkr.co/edit/Ld5xOX41km03zaIqd2nc?p=preview

Yours sincerely.

**Comment by swalters** [comment] 2015-03-10 17:21
This is also in 401 tutorial

**Comment by PaulL1** [comment] 2015-03-11 07:24
Duplicate of #2898

**Closed by PaulL1** 2015-03-11 07:24 UTC
Labels: Hi-Pri Bug
