### ISSUE TITLE
Auto resize causes the grid to dance on a page

### ISSUE THREAD

**Issue by killyosaur** [angular-ui/ng-grid#2929] opened 2015-03-06 12:51 UTC
So there is an issue with the grid's resize feature where it is attempting to calculate it's height and width and if other elements on the page cause the Scroll bar to disappear after initial load, the grid will start dancing (resizing by the amount of the width of the browser scroll bar). This happens in Chrome and all versions of IE. Also, the height calculation doesn't play nice with dynamically changing data and will often miscalculate its height.

**Comment by PaulL1** [comment] 2015-03-06 18:21
Is this a duplicate of #2930 - both opened at similar times?

**Comment by PaulL1** [comment] 2015-03-09 05:40
I think this is duplicate, so I'm closing.

**Closed by PaulL1** 2015-03-09 05:40 UTC
Labels: duplicate, waiting-response
