### ISSUE TITLE
To deselect the selected row in ng-grid

### ISSUE THREAD

**Issue by VenkatRamNDD** [angular-ui/ng-grid#2743] opened 2015-02-11 09:23 UTC
I have a ng-grid in my page when i select a row in the ng-grid still i leave the page the selection of a row is maintained but i need, once i select the row in ng-grid if i do some(any) other action in my page it should be deselected.

This is my plunker: http://plnkr.co/edit/cZLP2A3W6bKI1bzllj1C

**Comment by PaulL1** [comment] 2015-02-11 19:06
Duplicate of #2747?

**Closed by PaulL1** 2015-02-11 19:06 UTC
Labels: duplicate
