### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by dlukianenko** [angular-ui/ng-grid#3229] opened 2015-04-07 19:08 UTC
Hello, I face time to time issue when my ui-grid missing header and load only grid "body". Please take a look at screenshot http://i.imgur.com/f90XYiA.png
What could be a reason of that and how I can fix it?

Thank you

**Comment by c0bra** [comment] 2015-04-07 21:34
It looks the header itself is present, but maybe the header cell contents themselves are missing?

It's hard to tell from your image as the grid appears to be heavily customized. Could you annotate it or a new image to show where you expect the missing contents to be seen, visually?

**Comment by dlukianenko** [comment] 2015-04-07 22:51
I'm using my custom header cell templates and I load them. It happens that firstly ui-grid body cells templates loads and then header cell templates. Sometimes the header shows, sometimes not and I can't figure out why it happens. Here's example when it works like supposed to http://i.imgur.com/Z0dVdim.png, and here is pictures what  has been loaded http://i.imgur.com/2yg8NX3.png (loaded body cells templates first) then http://i.imgur.com/YtRZrbs.png ( rowTemplate and headerCellTemplates ) then it load some other stuff.

When the header missing we have exactly the same templates load order 
http://i.imgur.com/ckZEBZX.png http://i.imgur.com/As3LtKt.png and also as you can see the html content is present inside the query http://i.imgur.com/1xgn1c7.png but it doesn't apply to ui-grid http://i.imgur.com/IfBDvgg.png. That is my code which I use to define header templates and the path to them http://i.imgur.com/NpA7TVO.png

Could you give me some ideas why it happens? Because that is strange to me. What is the most interesting it happens time to time. For example once in 5+ page reloads in Chrome.

**Comment by dlukianenko** [comment] 2015-04-07 22:58
Also sometimes it loads partially like this http://i.imgur.com/VS1mw2w.png

**Comment by PaulL1** [comment] 2015-05-16 06:27
Are you able to provide a plunker for this?  It's hard to debug from screen shots.

**Comment by PaulL1** [comment] 2015-06-06 01:11
More information sought, not forthcoming after 3 weeks, closing, please reopen or reraise if this is still an issue for you.

**Closed by PaulL1** 2015-06-06 01:11 UTC
Labels: waiting-response

**Comment by spencer48** [comment] 2015-06-10 21:40
Hello! I am also experiencing this issue. @dlukianenko did you manage to find a solution?

**Comment by dlukianenko** [comment] 2015-06-10 21:53
No, I gave up and build my own custom grid
If you find the solution please let me know

**Comment by spencer48** [comment] 2015-06-11 21:39
Will do!

On Wed, Jun 10, 2015 at 2:54 PM, dlukianenko <notifications@github.com>
wrote:

> No, I gave up and build my own custom grid
> If you find the solution please let me know
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/3229#issuecomment-110927265>
> .
>



-- 
*Spencer*

**Comment by marcus-r** [comment] 2016-01-15 13:32
I had the same issue... Including the templates as hard coded strings instead of lazy loading them solved it for me. Hard coded strings are also used for the default ui-grid templates. I don't think ui-grid actually fully supports template loading? Can't find anything about it in documentation at least, could somebody else have to confirm that?

**Comment by AdrianLungu** [comment] 2016-08-23 17:44
I'm not sure if this is exactly the same issue I've run into.

It seems that when the UI-Grid is set to use html files as templates, some of them are not properly instantiated. Using version 3.2.1, at line 1038 in ui-grid.js, it seems that the first time my grid is loading, the headers that have custom templates are seen as undefined. 

When I scroll and the grid reloads the respective headers, they appear ok. It's only on page load that they are undefined. I'm still digging to see what could be the cause of this.

**Comment by rosslyn-adambielasty** [comment] 2016-09-14 10:36
I was able to fix similar problem [here](http://stackoverflow.com/questions/39410493/columndefs-header-does-not-show-from-time-to-time)

**Comment by karthik2901** [comment] 2017-02-20 11:33
I am a normal github user.I can't reopen the issue.I'm requesting @PaulL1  or @c0bra to reopen the issue.The issue is still there

**Comment by karthik2901** [comment] 2017-02-20 13:29
I'm using version 3.2.1
