### ISSUE TITLE
Strange column header height

### ISSUE THREAD

**Issue by reidlai** [angular-ui/ng-grid#2509] opened 2015-01-08 08:40 UTC
Dear All, 

I have the following html code fragment.

```html
<div class="container-fluid">
<div id="test1" class="default-route-grid" ui-grid="gridOptions" ui-grid-selection></div> 
</div>
```

and my gridOptions is same as below:

```javascript
$scope.gridOptions = {
            enableFiltering: true,
            enableSorting: true,
            enableRowSelection: true,
            enableSelectAll: false,
            selectionRowHeaderWidth: 35,
            multiSelect: false,
            columnDefs: _.map(_.filter($scope.columnDefs, function(item) { 
                return item.field;
            }), function(item) { 
                return item ;
            }),
            data: DataSync.getRows("dbv2-routes", function(item){
                return item.Status != "Archived";
            }),
            onRegisterApi: function(gridApi){                
                $scope.gridApi = gridApi;
                gridApi.selection.on.rowSelectionChanged($scope,function(row){
                    var selectedRows = gridApi.selection.getSelectedRows();
                    $scope.refreshButton("CopyRouteButton", selectedRows);
                    $scope.refreshButton("EditRouteButton", selectedRows);
                    $scope.refreshButton("DeleteRouteButton", selectedRows);
                });
            }
        };
```

Everything works fine except the column header height grows near half of the whole grid.  I have no idea what happened.  Is there anyone can tell how to set column header height?  Is there any way the column header height is adjusted automatically?  Thanks for your advice.

**Comment by PaulL1** [comment] 2015-01-08 21:58
What version are you using?  We had this issue earlier in the development cycle, I believe the current master no longer has it.  Could you try building from master and see if the problem persists?

**Comment by reidlai** [comment] 2015-01-09 01:36
I am using 3.0.0-rc16 with angularjs 1.3.8.  I tried to clone ng-grid.git master and build by grunt.  The build is successful but the case still exists.  I also test in both Chrome and Firebox...it won't help to identify problem except that I add css class ui-grid-top-panel in my app stylesheet to override your class with max-height setting but ui-grid filtering features does not work due to restrited header height and other div setting.

**Comment by PaulL1** [comment] 2015-01-09 02:33
OK, I think rc16 might pre-date the angularJS 1.3 support.  I'd suggest getting to at least rc18, but preferably build from source.

**Comment by reidlai** [comment] 2015-01-09 02:51
I did try to build from master...but no help.

**Comment by PaulL1** [comment] 2015-01-09 02:58
OK, are you able to provide a plunker that illustrates the issue, which would allow us to diagnose?

**Comment by pedroclayman** [comment] 2015-01-16 15:51
I am experiencing similar behaviour. While scrolling down (or up) the header keeps growing.
(I have checked out the latest version from the master and built it). What keeps growing is the height being set to the following CSS selector: .grid1421422637933 .ui-grid-render-container-body .ui-grid-header-cell.

**Comment by sandeeproop** [comment] 2015-01-20 05:39
I am able to reproduce this behavior on 
http://ui-grid.info/docs/#/tutorial/103_filtering
I am using Firefox 27.0.1

**Comment by coffeetime96** [comment] 2015-01-30 16:35
facing the same issue, any solution or hint on how to solve this, please.

**Comment by pyrostrex** [comment] 2015-02-02 06:40
I also had this problem, after hours of trying to get the tutorial to work properly, it turns out I, all i have to do is to put "<!doctype html>"

**Comment by regoarrarr** [comment] 2015-02-07 01:17
I have the same problem - http://www.pointswithacrew.com/mile-matrix

**Comment by c0bra** [comment] 2015-02-23 23:19
This should be fixed in unstable, various header height calculation fixes have gone in. Can anyone confirm?

**Comment by dilip-borad** [comment] 2015-03-08 22:13
Thanks @pyrostrex 
Now it's works for me after add this "<!doctype html>" on top of the HTML page.

**Comment by c0bra** [comment] 2015-03-30 20:16
I'm going to go ahead and close; if it's still a problem, please open a new issue.

**Closed by c0bra** 2015-03-30 20:16 UTC
Labels: waiting-response

**Comment by fahadash** [comment] 2015-10-12 03:51
@pyrostrex  You are my hero!

**Comment by bestic** [comment] 2015-12-02 10:41
@pyrostrex Thank you!

**Comment by brucebetts** [comment] 2016-02-02 16:57
I had the same problem as @reidlai using 3.1.0.6709847.  It was driving me CRAZY, trying everything.  I am a newbie, so always assumed that it was some coding or set up error.  It ran just fine in straight forward Angular app, but wouldn't run in a Laravel setup, even bypassing laravel's blade, etc.  Ui-grid  was ignoring css file entirely.  Four days later I ran across this chat stream -  added <!doctype html> to my php file - thx @pyrostrex!  It would be helpful to document this requirement to the ui-grid tutorial.

**Comment by desflan** [comment] 2016-11-24 05:51
@pyrostrex that fix still works!!

**Comment by uhe1896** [comment] 2016-12-22 03:06
@pyrostrex you are my hero too, thanks

**Comment by windmaomao** [comment] 2017-02-14 15:26
thank you, this is going nuts on me

**Comment by prabhakarreddy1234** [comment] 2017-03-06 17:27
thank you so much @pyrostrex .. I spend few hours to figure it out....

**Comment by ryanpiv** [comment] 2017-04-13 15:55
@pyrostrex you are a legend

**Comment by saicharan902** [comment] 2018-08-23 06:44
@pyrostrex  Thanks a lot

**Comment by shrawanibharati** [comment] 2019-11-21 07:06
@pyrostrex you are a hero
