### ISSUE TITLE
Is it possible to change css classes which get executed on runtime for ui-grid?

### ISSUE THREAD

**Issue by mohitgupta2209** [angular-ui/ng-grid#3465] opened 2015-05-11 06:25 UTC
I have a "ui-grid-render-container-body" & "ui-grid-viewport" class which is acting wierd due to which the grid scales outside the desired container.. how can we control this?

![snip](https://cloud.githubusercontent.com/assets/9722364/7559439/b0976126-f7d4-11e4-8500-16a4db1677ba.JPG)

**Comment by PaulL1** [comment] 2015-05-16 04:50
It's hard to see what the problem is based on the information you provided.  Are you saying that you're overriding the css classes, and then not getting the desired behaviour?  Or is something else causing your issues?

Perhaps you could provide a plunker of your issue, and explain what the behaviour is that you're getting and what you expected to get instead?

**Comment by PaulL1** [comment] 2015-06-06 01:10
More information sought, not forthcoming after 3 weeks.  Closing, please reopen or re-raise if this is still an issue for you.

**Closed by PaulL1** 2015-06-06 01:10 UTC
Labels: waiting-response
