### ISSUE TITLE
Drag and rop row to change order

### ISSUE THREAD

**Issue by myalban** [angular-ui/ng-grid#3072] opened 2015-03-20 15:22 UTC
Hi,

Does it exist a function to do a drag and drop  rows to change and save order ?

Thanks

**Comment by LeonanCarvalho** [comment] 2015-03-20 15:33
It don't make sense, are you talking about drag and drop to change GROUPING?

**Comment by PaulL1** [comment] 2015-03-20 20:14
Duplicate of #1359.  This feature isn't implemented, and isn't in the near-term roadmap unless someone wants to submit a conforming PR.

**Closed by PaulL1** 2015-03-20 20:14 UTC
