### ISSUE TITLE
UI-grid filtering seems very laggy with large (45,000 row) dataset

### ISSUE THREAD

**Issue by regoarrarr** [angular-ui/ng-grid#2574] opened 2015-01-16 14:19 UTC
I have a large dataset that I was using with ng-grid.  It has 46,000 or so rows which I know is a lot, but it was filtering okay in ng-grid.  I was using a custom filter to filter the origin and destination countries but now I converted to use the new ui-grid and the built-in filter.

So I don't know if I perhaps just missed a configuration, or if the performance with ultra-large datasets is not as good.  I saw that there was an option to only show the results that are actually on the grid?  It seems that most of the lag is trying to update the entire grid.

Working prototype is at http://milematrix.pointswithacrew.com

**Comment by c0bra** [comment] 2015-01-16 15:08
You should try updating to a newer version. rc.3 is from September of last year; there's been a lot of changes since then.

**Comment by regoarrarr** [comment] 2015-01-16 16:26
Thanks for the reply - I went with rc.3 as that was what was listed under "stable".  Unfortunately, I upgraded locally to RC18 and still experienced the same lag in filtering

**Comment by PaulL1** [comment] 2015-01-16 22:01
Plunker demonstrating the problem: http://plnkr.co/edit/Mp7I2yMQADMTPAETL0KD?p=preview (this is the large dataset tutorial with filtering turned on, and the data added 4 times to get 40,000 rows instead of 10,000).

It is slow, and I presume it's because we're filtering on every keypress.  I'll see what profiling tools I can find that will suggest where the problem may be.

**Comment by regoarrarr** [comment] 2015-01-19 00:35
Great!  So what's the best way to pull the code with the latest patch?  Are release candidates done in a timely fashion, or am I better off pulling?

**Comment by regoarrarr** [comment] 2015-01-19 15:30
Pulled down the latest 3.0-RC18 and can confirm that it is no longer laggy.  Thanks for the super fast response!

**Comment by 2fdevs** [comment] 2015-03-12 13:55
@PaulL1 I saw your example and I'm experiencing the same performance problems as in my app.

Steps to reproduce the problem:
1. Open http://plnkr.co/edit/Mp7I2yMQADMTPAETL0KD?p=preview
2. Sort the column age.
3. Search for "sam" in column "Name".

The search is really sluggish, I'm working on a fix for this sort+filter problem but any help is more than welcome.

**Comment by 2fdevs** [comment] 2015-03-12 16:26
By modifying this function to just return `oldRows` I've earned like 6 seconds in my search (20K rows).

```js
Grid.prototype.getDeletedRows = function(oldRows, newRows) {
    /*var self = this;
    var olds = oldRows.filter(function (oldRow) {
      return !newRows.some(function (newItem) {
          count++;
        return self.options.rowEquality(newItem, oldRow.entity);
      });
    });*/

    // var olds = self.newInN(newRows, oldRows, null, 'entity');
    // dump('olds', olds);
    return oldRows;
  };
```

But I don't know exactly how it works and what problems could happen with this modification. Any core team could shed some light on this?

**Comment by 2fdevs** [comment] 2015-03-12 16:32
BTW, for those who need to do this without modifying the ui-grid.js (if you plan to release with jenkins for example) you can modify the getDeletedRows function through the API:

```js
scope.gridOptions.onRegisterApi = function(API) {
    gridAPI = API;

    gridAPI.grid.getDeletedRows = function getDeletedRows(oldRows, newRows) {
        return oldRows;
    };
};
```

**Comment by novice3030** [comment] 2015-03-12 16:55
I think we need to debounce the user input so we won't filter until the
user is done typing
That might gain some performance

2015-03-12 18:32 GMT+02:00 Two Fucking Developers <notifications@github.com>
:

**Comment by PaulL1** [comment] 2015-03-12 18:37
Someone said that angular 1.3 already automatically debounces if you type fast enough, and I thought for most cases that it was now fast enough.  Is there still a problem with filter performance?

**Comment by 2fdevs** [comment] 2015-03-13 08:29
It's not a problem that could be solved with debouncing, because if you type just one char (like "s" instead of "sam") the search becomes slow.

We spent a few hours on this yesterday and we realized that the `getDeletedRows` is really unperformant (however, we still don't know how to make it smoother). For example, we modified the code and did some performance tests:

```js
  Grid.prototype.getDeletedRows = function(oldRows, newRows) {
    var self = this;
    var count = 0;
    console.time("getDeletedRows");
    var olds = oldRows.filter(function (oldRow) {
      return !newRows.some(function (newItem) {
        count++;
        return self.options.rowEquality(newItem, oldRow.entity);
      });
    });
    console.log(count);
    console.log(oldRows.length + "/" + newRows.length + " vs " + olds.length);
    console.timeEnd("getDeletedRows");
    // var olds = self.newInN(newRows, oldRows, null, 'entity');
    // dump('olds', olds);
    return olds;
  };
```

With a grid with 20K rows this was thrown to the console:

```
88174460
7354/11990 vs 7354
getDeletedRows: 10643.675ms
```

So the "some" function was called 88 million times and the complete method took almost 11 seconds to complete, which seems to me pretty unperformant.

We understand what is doing the `getDeletedRows` method, but we don't understand yet why it is necessary since it seems that the deleted rows are available in `unfoundOldRows`. Also, is important to notice that it doesn't found any deleted row.

Said that, we have a workaround by modifying the `getDeletedRows` but we're not very happy with that since we don't know if that function is needed for other features (probably yes), so it would be great to know why is this needed.

Oh, and thanks for the good job. The ui-grid is a great component, congratulations.

**Comment by PaulL1** [comment] 2015-03-13 08:54
According to my search of the code base, getDeletedRows is declared but never used.  So I'm not clear how it could be contributing to a performance problem with searching.  Are you on the latest version of ui-grid (i.e. is this old code that is no longer used?)

**Comment by 2fdevs** [comment] 2015-03-13 09:37
You can find a use inside `modifyRows` function here:

https://github.com/angular-ui/ng-grid/blob/23fec1743548c4a9cd87eedcdd81bb161ebcc130/src/js/core/factories/Grid.js#L1050

We're working on version (ui-grid - v3.0.0-rc.20 - 2015-02-24) which is the latest available as a tag on github.

**Comment by 2fdevs** [comment] 2015-03-13 09:44
Just in case it could help, we're working on Angular 1.3.14.

**Comment by PaulL1** [comment] 2015-03-13 19:04
Ah, OK, don't know why my search didn't find that.  :-)

So the deleted rows is being used to clean up the gridRows from the hashMap, otherwise they'd presumably represent a memory leak.  It's not clear to me why we need to remove them from the rows array, by definition they are not in there at this point anyway.

A lot of this code was added in a PR some time ago, 246025a9caf940bff88729bfd48fb207b14b4e3c, further code was added by @c0bra to add the hashMap logic: da87ff9a4082c0f9f8996d4bdb5225ce191392ef

Looking at the code I feel that it's kind of ugly, it seems like there should be a more elegant way to do things.  So we'd probably be open to a refactor and tidy up.  I think the key requirements of this code is that it:

- create new gridRows for any genuinely new data
- preserve the ordering to match the input data array where possible (if sorting isn't being applied)
- not leak memory

I think the hashMap was already a performance optimisation, it looks like a consequence of the hashMap is a need to manually tidy it up.  There may be a more efficient way to find the "unfound" rows - like perhaps keeping a copy of the old rows array, and removing each row from them as it's found perhaps.  Of course doing that on a flat array would be inefficient, so you'd probably have to put it into a hash first, then remove them as you find them, then at the end the ones left would be the deleted rows.

**Comment by PaulL1** [comment] 2015-03-13 19:57
Having said that, does sort call modifyRows?  It probably shouldn't - sorting doesn't create any new rows so there's no reason that modifyRows would get called.

**Comment by c0bra** [comment] 2015-03-13 20:53
Who you callin' ugly? ;)

Yes, this code sorely needs some TLC. It's always at the top of the complexity and un-maintainability chart on plato.

The problem we have is that when the data watch function is fired we have no idea what operation has been done. Data could be added, removed, re-ordered, replaced entirely, etc.

If we don't care about state then we can just wipe out everything and start over. But if we don't want to lose things like selection, we need to map from the new data array to the array we already have.  Part of this is making sure that any items we have left over in our old array that aren't in the new array are removed, and that's what `getDeletedRows` is doing.

**Comment by PaulL1** [comment] 2015-03-13 20:55
@2fdevs: for me the sort performance is heavily driven by the getCellValue.  If you aren't using complex binding, then you may find that you can change the rowSortFn:

```
        var propA = grid.getCellValue(rowA, col);
        var propB = grid.getCellValue(rowB, col);
```

becomes

```
        var propA = rowA.entity[col.field];
        var propB = rowB.entity[col.field];
```

For me that improves the sort function performance quite a bit.  I'm looking at some thoughts about how to apply that to the core code base.

**Comment by 2fdevs** [comment] 2015-03-13 23:17
Hi @PaulL1 and @c0bra, thanks for the explanations

I will test your suggestions on Monday at work and will tell you how it goes.

I will share here any discover. Thanks again for the good support :)

**Closed** 2015-03-14 21:05 UTC

**Comment by 2fdevs** [comment] 2015-03-14 21:18
So it seems that it was indeed the getCellValue method. I will test it on Monday, thanks again for the great support :)

**Comment by PaulL1** [comment] 2015-03-15 02:09
OK, final change, I've also simplified modifyRows.  In this case I'll wait for @c0bra's review, but I think it's correct and it removes the need for getDeletedRows, so probably should run faster when you're changing existing data.  It's PR #3014 if you wanted to try it out.

**Comment by 2fdevs** [comment] 2015-03-16 09:45
Hi Paul,

I've tested and it works quite faster but not as faster as when it is unordered. Anyway, it should work for now, so you can close this issue if you want :)

Thanks for the great support.

**Comment by PaulL1** [comment] 2015-03-16 18:28
Thanks @2fdevs.  Note that it will always be slower with a sort - a lot of the time is the raw javascript sort time, which is material when you have very large data sets.

**Comment by 2fdevs** [comment] 2015-03-16 18:36
Yes, I know, maybe a good option could be a WebWorker. Another option is to create an indexable dictionary, but I'm pretty sure that it's not a good option for mobile devices since it would produce a lot of memory allocation.

Probably in the future we will make a WebWorker for this, so I will tell you how it goes then and we can make a PR if you want.

**Comment by PaulL1** [comment] 2015-03-16 18:39
I don't think it's a great candidate for a webWorker, unless you're happy for a lag between clicking the sort icon and anything actually happening.  There's no way to render just the first 10 rows of a sort - you have to sort the whole dataset to know what the first 10 rows are.

If you're doing very large datasets and want sorts, I would have taken a look at infinite scroll or pagination, and pushed your sorting off to the server using external sorting.

**Comment by 2fdevs** [comment] 2015-03-16 19:00
For us that's not a problem, we will put just a loading icon when user will search or sort and that's all, so yes, we're happy with that :)

Anyway, thanks for all! Great support and great project!

**Comment by anilnatha** [comment] 2015-09-18 02:45
I know this ticket is closed and is dated, but I agree with @novice3030 in that adding a debounce for the filtering may indeed help. I've been running through various optimizations (i.e. 'fastWatch' and 'flatEntityAccess') to my grid setup that loads up approx 42K records with 8 columns of data and noticed that after sorting just one column, and then typing a four letter word in one of the filters, the filtering was triggered at different points in my tests. Sometimes it would trigger after only one letter was typed, other times after 3 letters.  Anytime the filter was triggered before I finished typing caused a delay before the final filtering could be finished, this amounted to about an extra 3-6 seconds. This is why adding a 'filterDebounce' IMO should help.

**Comment by SinghB** [comment] 2016-12-28 16:37
First off congratulations on superbly awesome component. Completely love it.
Ran today into this lag on filters problem and my grid made up of about 12 columns with data coming in from multiple related entities. Ultimately, in the grid I've about 190 rows but filter on any of the columns gave a very visually detectable lag. I'm putting down the comments here because I experience the performance improve by setting:

enablePaging: false
fastWatch: false

Now, the paging still is there on the grid, probably because of ui-grid-pagination. But setting the gridOptions.enablePaging to false did help improve the performance.

**Comment by petroleumrx** [comment] 2017-02-28 22:48
.
