### ISSUE TITLE
Group row header is shifting up when grid has filter row

### ISSUE THREAD

**Issue by vikh** [angular-ui/ng-grid#3524] opened 2015-05-18 15:19 UTC
On tutorial page http://ui-grid.info/docs/#/tutorial/209_grouping if you click on any group header to expand the group, all group icons are shifting up one row. It looks like it is related to the fact that grid has filter row.

**Comment by PaulL1** [comment] 2015-05-18 18:11
Duplicate of #3394

**Closed by PaulL1** 2015-05-18 18:11 UTC
