### ISSUE TITLE
Problem with scope in custom directive used in cellTemplate

### ISSUE THREAD

**Issue by bryanbak** [angular-ui/ng-grid#3305] opened 2015-04-17 17:01 UTC
I'm trying to use a custom directive in a cellTemplate and pass data to it from the row.entity. It appears to be working except for any new scope variable that the directive creates (via the directive controller or link functions). Everything looks right initially, but as I scroll down in the grid the new scope variables that I have created start getting the values passed in for previous rows in the grid.

I'm not sure that I can explain it much better than that so I created a stripped down plunker that shows what's happening: http://plnkr.co/edit/7r74eYHx3PpZesMIqumA?p=preview

I'm a little new to custom directives so I'm not positive if this is a bug in my directive, the grid, or maybe I'm just passing data from the grid to the directive in the wrong way. I just know that when I switched it around to be a simple table rather than grid I didn't have any issues. Thanks for any help!

**Comment by PaulL1** [comment] 2015-04-17 19:16
That sounds like a problem with row virtualisation.  The grid doesn't actually render all the (potentially thousands) of rows - it renders only those that are visible.  As you scroll we are rendering the extra rows to make it look like they were always all rendered.  This is good for performance, but it would mean that when we scroll we're creating new DOM elements on the fly.  To avoid that, we reuse the existing DOM elements, and we just move the scroll around to make it look like it's scrolling.

TL:DR, the row and col that a particular html element refers to changes as you scroll.  That'll be what's messing up your $scope.

Looking at the code, I think you're trying to find a way to get directly at the row.entity without having to pass it in as a parameter on your directive (because bar is working, but I think you want foo to work).  The problem is that foo is taking a copy of the id at a point in time, and it has no way to notice when it changes.  If you modify it to grab the current id whenever it renders, then it works: http://plnkr.co/edit/WSVjRFY56OrCtCWNT3Rt?p=preview

**Comment by bryanbak** [comment] 2015-04-17 20:12
Thanks for the quick response.

I had a feeling it had to do with row virtualization, but I didn't know much about how that works. I'm hesitant about accessing the row via the $parent scope from the directive as that would make my directive tied to ui-grid and I plan on using it in other places as well.

Do you think it might work better to watch my passed in directive variables and reinitialize the directive when they change (i.e. `$scope.$watch('bar', reInitialize);`)? It appears to work in plunker, but I'm not sure if that would cause me any other issues down the line.

Here's the updated plunker: http://plnkr.co/edit/7r74eYHx3PpZesMIqumA?p=preview

**Comment by PaulL1** [comment] 2015-04-17 20:20
The main issue with watches is expense - they slow the application down.  We spend a lot of time trying to reduce watches (sometimes unsuccessfully).

I'd pass it in as you were doing with bar.  That works well.

**Comment by PaulL1** [comment] 2015-05-16 06:37
Looks resolved, closing.

**Closed by PaulL1** 2015-05-16 06:37 UTC
Labels: waiting-response
