### ISSUE TITLE
Expand all rows prevents user from clicking into an editable cell

### ISSUE THREAD

**Issue by roguezedd** [angular-ui/ng-grid#2766] opened 2015-02-13 01:54 UTC
Using a grid configured to navigate and edit cells. Expand all rows, 50 rows. Scroll to the bottom. Attempt to click and enter into a cell's edit mode. Strange behavior results. The user is unable to edit the cell and it seems like the grid is scrolling, or redrawing.

**Comment by PaulL1** [comment] 2015-02-13 23:27
Duplicate of #2755

**Closed** 2015-02-13 23:27 UTC
Labels: duplicate
