### ISSUE TITLE
[BUG] height of grouping expand all and select all button

### ISSUE THREAD

**Issue by edenchen123** [angular-ui/ng-grid#3439] opened 2015-05-07 09:00 UTC
The height of grouping expand all button changed after scrolling which cause expand button and it's row not in the same line. expand A open B....

see the official demo:
http://ui-grid.info/docs/#/tutorial/209_grouping

**Comment by mmautner** [comment] 2015-05-07 14:50
Can you clarify what you're describing? Maybe with a screenshot?

I'm not experiencing what I understand you are describing. Is this occurring for you in multiple browsers?

**Comment by AgDude** [comment] 2015-05-07 16:20
My guess it that this is another duplicate of #3394. If not, please provide some screenshots, as suggested earlier.

**Comment by edenchen123** [comment] 2015-05-08 01:43
yes  it's duplicated of #3394 .

**Comment by mmautner** [comment] 2015-05-08 02:48
then you should probably close this one then @edenchen123 :)

**Closed** 2015-05-09 13:43 UTC
