### ISSUE TITLE
Grouping with Filtering AND Column reordering causes an issue.

### ISSUE THREAD

**Issue by venbal** [angular-ui/ng-grid#3505] opened 2015-05-14 18:32 UTC
Please take a look at this sample code =>

http://plnkr.co/edit/GPbHJkWujaecHjTFwFLD

Issue (1) Open and Close of any "grouping", messes up the "+" sign because of the Filtering option on the top (works without Filter option)

Issue (2) The column reordering does not work properly, i.e. the animation is messed up

Please let me now how to fix these issues or is it a bug in the lib?

It looks like if I remove "ui-grid-grouping" directive, the column reordering works.. but obviously "grouping" is missing.

**Comment by AgDude** [comment] 2015-05-14 21:44
I believe (1) is a duplicate of #3394 
And (2) is a duplicate of #3395.
Both have pending pull requests which resolve the issues.

**Closed by AgDude** 2015-05-14 21:44 UTC
