### ISSUE TITLE
ui-grid-selection deselect using cmd click when in noUnselect.

### ISSUE THREAD

**Issue by j-walker23** [angular-ui/ng-grid#2100] opened 2014-11-14 13:16 UTC
With modifierKeysToMultiSelect: true cmd click to select items works awesome. Thank you.

When noUnselect: false, cmd deselect is working. When true it fails, nothing happens. Is this by design? If so is there config around it?

I just edited the selection plunker and set `$scope.gridOptions.noUnselect = true;` in `MainCtrl` to see what i mean.

Thanks again.

**Comment by PaulL1** [comment] 2015-02-01 06:07
OK, finally getting around to looking at this.

I understand the concept - which is that whilst you're selecting something if you make a mistake you should be able to unselect it again.  The problem is that noUnselect aims to not let you unselect things.  We're adding things to the selected list as you click on them, it's quite hard to draw a distinction between something that you accidentally added and should be allowed to remove and something that you added on purpose and shouldn't be allowed to remove.

We could arguably change the semantics so that noUnselect really means "you cannot unselect the last item".  So we'd let you unselect as long as at least one item was still selected.  That would sort of make sense, but I'm not sure how much demand there would be for it - it seems to me that if you are setting 'noUnselect' you probably don't want people to be able to unselect anything.

**Comment by PaulL1** [comment] 2015-05-27 06:58
No further comment on this, I'm not sure it's possible.  Closing.

**Closed by PaulL1** 2015-05-27 06:58 UTC
Labels: enhancement

**Comment by j-walker23** [comment] 2015-05-27 17:45
@PaulL1 No need to open this back up, sorry i never saw it.
Just curious if we are on the same page.

Here is the scenario. 
Grid with multi select on and the `shift + cmd` coolness for selecting rows.
Lets say i pick and choose 20 rows out of 30 to do a specific action to those 20. 
I then realize that i only need 19 of them. I can not hold `cmd` + `click` to deselect one of the rows that is selected.

When `noUnselect` is false i can select and deselect while holding `cmd` on keyboard. Just like one would in Finder on the osx when selectively choosing files to be deleted.

When `noUnselect` is true i cannot deselect any rows without some type of grid refresh. I thought noUnselect being true was only suppose to disallow me from deselecting the last selected row.

And please know that i am not saying i know ui-grid is wrong, i just had thought i would be able to "toggle" rows off and on, unless it was the last one. 

Am i misunderstanding `noUnselect`?
