### ISSUE TITLE
data load callback

### ISSUE THREAD

**Issue by feralanPaladin** [angular-ui/ng-grid#3285] opened 2015-04-15 12:07 UTC
Hi, 

Is there any callback mechanisms to trigger me after data load(change) operations.
2.x version has dataUpdated option for this kind of operations (Its comment says : Data updated callback, fires every time the data is modified from outside )

**Comment by c0bra** [comment] 2015-04-16 22:42
I don't think there's any callback for that currently. Why would it not work to do your action inside your app based on the change?  Is there any scenario where data changing is initiated from inside the grid never exposed to your app?  I have yet to see a use case where the data going in to the grid is out of the control and vision of the parent application.

It wouldn't be hard to add the callback though, if it were really needed.

**Comment by feralanPaladin** [comment] 2015-04-17 05:31
Actually you're right. Now I am using cellTemplates to handle data update
feedbacks ( I try to apply Robin Herbot's InputMask library on grid cells)
But now, I am facing a few performance issues. Sorting speed is is one of
them as each grid cell applies the desired mask on its div)
Does ui grid has a mask or render option for the cells?

2015-04-17 1:43 GMT+03:00 Brian Hann <notifications@github.com>:

> I don't think there's any callback for that currently. Why would it not
> work to do your action inside your app based on the change? Is there any
> scenario where data changing is initiated from inside the grid never
> exposed to your app? I have yet to see a use case where the data going in
> to the grid is out of the control and vision of the parent application.
>
> It wouldn't be hard to add the callback though, if it were really needed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/3285#issuecomment-93855688>.
>



-- 
Onur DESTANOGLU

**Comment by PaulL1** [comment] 2015-04-17 05:47
You shouldn't need to use cellTemplates to handle data update.  There should be two scenarios:

1.  The data is changed programatically from outside the grid.  In this situation you know that you changed the data, so you can take actions as appropriate when you change it (usually you do a $timeout so that the grid has the time to ingest the data, then do your action)
2.  The data is edited inside the grid.  In this scenario you should use the edit feature, and you should provide the END_CELL_EDIT event if you're using custom editors.  This event will call notifyDataChange, which tells the grid the data is updated.

From your description it sounds like you've put custom templates into each cell with that template having an editor inside it along with some logic.  The problem is that all that logic is going to run on every tick of every scroll event, which isn't what you want.  That's why the edit feature only puts the editor into the cell when someone actually clicks on it.

**Comment by feralanPaladin** [comment] 2015-04-17 06:16
Hi,

First of all thank you for your earliest response :)

This is my addition into the column definitions;
cellTemplate: "<div maskable='" + scope.model.columns[i].id + "'
class='ui-grid-cell-contents' title='" +
scope.model.columns[i].model.placeHolder + "'
ng-model='MODEL_COL_FIELD'></div>"

Actually this is the same cellTemplate that the default mechanism uses with
a few changes.
1- It uses an ng-model, not an expression
2- It uses an maskable directive which applies mask after every change in
the MODEL_COL_FIELD

So the masking logic does not run on every tick of every scroll event. It
just runs on sort, filter and initial load events (also on paging)

And this is the reason why I feel that I have to use an cellTemplate to
handle mask updates; I can not manage to catch sort, filter and initial
load event's endings. And thats why I've ask you for an data load complete
event.

May I have any further valuable suggestions of yours please.

Thank you

2015-04-17 8:47 GMT+03:00 Paul <notifications@github.com>:

> You shouldn't need to use cellTemplates to handle data update. There
> should be two scenarios:
>
>    1. The data is changed programatically from outside the grid. In this
>    situation you know that you changed the data, so you can take actions as
>    appropriate when you change it (usually you do a $timeout so that the grid
>    has the time to ingest the data, then do your action)
>    2. The data is edited inside the grid. In this scenario you should use
>    the edit feature, and you should provide the END_CELL_EDIT event if you're
>    using custom editors. This event will call notifyDataChange, which tells
>    the grid the data is updated.
>
> From your description it sounds like you've put custom templates into each
> cell with that template having an editor inside it along with some logic.
> The problem is that all that logic is going to run on every tick of every
> scroll event, which isn't what you want. That's why the edit feature only
> puts the editor into the cell when someone actually clicks on it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/3285#issuecomment-93898316>.
>



-- 
Onur DESTANOGLU

**Comment by PaulL1** [comment] 2015-04-17 06:26
What exactly does the mask do?  Is it something you could do with a cellFilter instead?  For example, we'd often use a cellFilter to format dates, that sounds sort of like what you're doing - but it depends what you mean by mask.

If what you're doing is something like formatting a credit card number for example (so it's 000-000000-000 or something like that), then the code would be something like:

```
  colDefs = [
    { name: 'creditCard', cellFilter: 'maskCreditCard' }
  ];
  
  ....
.filter('maskCreditCard', function() {
  return function(input) {
    if (!input){
      return '';
    } else {
      var firstThree = input.subStr(0,3);
      var nextSix = input.subStr(3,6);
      var lastThree = input.subStr(9,3);
      return firstThree + '-' + nextSix + '-' + lastThree;
    }
  };
})
```
We use a cellFilter in http://ui-grid.info/docs/#/tutorial/201_editable if you want an example to look at (in that case we're mapping a code 1 or 2 to a gender male or female).

**Comment by feralanPaladin** [comment] 2015-04-17 06:34
I am also using cell filters in my application to handle gender-like issues
(I am printgin Yes for data value 1, and No for data value 0)

Here is my maskable directive;
angApp.directive( "maskable", ["sfsUtilFactory", "sfsMaskService", function
( sfsUtilFactory, sfsMaskService ) {
    return {
        restrict: 'A',
        require: "ngModel",
        link: function ( scope, element, attr, ngModelController ) {
            ngModelController.$render = function () {
                if ( !ngModelController.$isEmpty(
ngModelController.$viewValue ) ) {
                    element.html( ngModelController.$viewValue );
                } else {
                    element.html( "" );
                }

                var elementModel = sfsUtilFactory.getControllerModel(
element.attr( "maskable" ) );

                sfsMaskService.implementType( elementModel.typeSpec.type,
$( element ), sfsUtilFactory.logic.culturalData.languageCode[0], true );
            };
        }
    };
} ] );

It just accepts an ng-model and applies a mask on it. As an example;
-Column number 4 includes currency data and it should be masked according
to the localization data
Data Value => 123456789
Printed Value if the Turkish localization is selected => TL 123.456.789,00
Printed Value if the Indian localization is selected => RP 12.34.56.789,00

Does the cell filter can handle this?

2015-04-17 9:26 GMT+03:00 Paul <notifications@github.com>:

> What exactly does the mask do? Is it something you could do with a
> cellFilter instead? For example, we'd often use a cellFilter to format
> dates, that sounds sort of like what you're doing - but it depends what you
> mean by mask.
>
> If what you're doing is something like formatting a credit card number for
> example (so it's 000-000000-000 or something like that), then the code
> would be something like:
>
>   colDefs = [
>     { name: 'creditCard', cellFilter: 'maskCreditCard' }
>   ];
>
>   ....
> .filter('maskCreditCard', function() {
>   return function(input) {
>     if (!input){
>       return '';
>     } else {
>       var firstThree = input.subStr(0,3);
>       var nextSix = input.subStr(3,6);
>       var lastThree = input.subStr(9,3);
>       return firstThree + '-' + nextSix + '-' + lastThree;
>     }
>   };
> })
>
> We use a cellFilter in http://ui-grid.info/docs/#/tutorial/201_editable
> if you want an example to look at (in that case we're mapping a code 1 or 2
> to a gender male or female).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/3285#issuecomment-93906273>.
>



-- 
Onur DESTANOGLU

**Comment by PaulL1** [comment] 2015-04-17 06:58
Yes, cellFilter can do that.  It's one of the things that it's for.  In fact, if you're doing currency, there's a native AngularJS currency filter that does it automatically.

**Comment by feralanPaladin** [comment] 2015-04-17 07:04
Thank you Paul.

2015-04-17 9:58 GMT+03:00 Paul <notifications@github.com>:

> Yes, cellFilter can do that. It's one of the things that it's for. In
> fact, if you're doing currency, there's a native AngularJS currency filter
> that does it automatically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/ng-grid/issues/3285#issuecomment-93919466>.
>



-- 
Onur DESTANOGLU

**Comment by tpkover** [comment] 2015-04-22 01:54
In regards to the data load callback, I was just looking for that very thing. In my case, I would like to  programmatically select a specific row immediately upon page load. However, I've been unable to find a reliable way to determine when it is safe to make the selection. Unless I've overlooked another way to trigger the row selection, a data load callback seems like a reasonable solution.

**Comment by PaulL1** [comment] 2015-04-22 02:12
I think we do this in the selection tutorial.  After you give the data to the grid you do a $timeout(0), and then do the row selection.

**Comment by tpkover** [comment] 2015-04-22 02:50
Thanks both for the quick reply and for pointing out the solution I had overlooked.

**Comment by PaulL1** [comment] 2015-05-25 23:53
I think this sounds resolved, closing.

**Closed by PaulL1** 2015-05-25 23:53 UTC
Labels: waiting-response
