### ISSUE TITLE
Pagination does not work 

### ISSUE THREAD

**Issue by vuhailuyen1991** [angular-ui/ng-grid#2479] opened 2015-01-04 08:25 UTC
My app dependencies: 
```javascript
window.ethnicApp = angular.module 'ethnicApp', ['templates', 'ngRoute', 'ngResource', 'ui.router', 'angular-loading-bar',
                                                'angularFileUpload', 'ngAnimate', 'ui.grid', 'angular-underscore', 'ui.grid.pagination',
                                                'authModule', 'homeModule', 'itemsModule',
                                                'addItemModule', 'showItemModule']

```

My html
```html
.grid ui-grid="itemsGridOptions" external-scopes='itemActionsManager' ui-grid-pagination=""

```
My Controller: 
```javascript
 $scope.itemsGridOptions = {
      paginationPageSizes: [10, 20, 30],
      paginationPageSize: 10,
      columnDefs: [
        { name: 'id' }
        { name: 'name' }
        { name: 'description' }
        { name: 'total_likes', displayName: '#Likes'}
        { name: 'seller.email' }
        { name: 'actions', displayName: 'Actions', cellTemplate: 'app/Items/Index/SubViews/ItemAction.html' }
      ]
    }
```

The page just show a table with 10 rows. No pagination sections at the bottom

**Comment by extdevelopment** [comment] 2015-01-04 23:35
Im in same situation.
Very confused paging and pagination name.
Something happened here?!, Merge pagination and paging features: https://github.com/angular-ui/ng-grid/commit/f8a68ccf7601a1a20f6b5234ad4fcaffa9f7a6fc
It works for me with paging with v3.0.0-RC.18
<pre>
$scope.gridOptions = { 
   enablePaging: true,
   pagingPageSizes: [10, 20, 30],
   pagingPageSize: 10,
</pre>

<pre>
angular.module('angularSonataAdmin', [ 'ui.grid.paging' ,'ngRoute', 'ui.grid', 'ui.grid.edit', 'ui.grid.resizeColumns', 'ui.grid.selection']
</pre>

<pre>
 div class="gridStyle" ui-grid="gridOptions" ui-grid-paging ui-grid-edit ui-grid-resize-columns ui-grid-selection
</pre>

I hope I helped, but I do not know how to change the code later.

**Comment by extdevelopment** [comment] 2015-01-05 17:14
Try ui-grid - v3.0.0-RC.18-f8a68cc - 2015-01-02 https://github.com/angular-ui/ng-grid/commit/f8a68ccf7601a1a20f6b5234ad4fcaffa9f7a6fc
This version works with pagination

**Comment by vuhailuyen1991** [comment] 2015-01-05 17:16
Thanks @extdevelopment

**Comment by alexandery** [comment] 2015-01-05 18:14
So, just recently there were 2 modules - pagination and paging. Even back then ui.grid.paging wasn't always included into the JS file. 'Stable' RC-18 still has ui.grid.paging, while latest 'unstable' version (v3.0.0-RC.18-f8a68cc) doesn't have it anymore.

It seems that pagination took over from paging, but it works somewhat different. Plus, I'm getting all sorts of issues on IE9 with pagination now - displaying only few rows (out of 50 per many hundreds of pages), styling is all messed up. Not really sure as to why this switch was done.

**Comment by futurechan** [comment] 2015-01-07 19:40
I'm also having an issue with external pagination. In ```onRegisterApi```, I try to setup my ```paginationChanged``` event handler, but in ``` gridApi.pagination.on.paginationChanged``` ```pagination``` is undefined. I do have ```userExternalPagination``` set to true.

**Comment by extdevelopment** [comment] 2015-01-07 19:59
useExternalPagination: true, 
not use(r)ExternalPagination, but possible a typo in comment.

I use this code, and working properly.
<pre>
    $scope.gridOptions.onRegisterApi = function(gridApi){
			gridApi.pagination.on.paginationChanged($scope, function (pageNumber, pageSize) {
				console.log('pager get data: pageNumber, pageSize', pageNumber, pageSize);
				getPager(pageNumber, pageSize); 
			});
    };
</pre>

**Comment by futurechan** [comment] 2015-01-07 21:36
@extdevelopment  Yeah, it was just a typo. I'm using rc16. It looks like I need rc18. I ran ```bower install angular-ui-grid --save```. Do I need to do something else?

**Comment by extdevelopment** [comment] 2015-01-07 23:28
I think bower download only "main" release. 
You need it http://ui-grid.info/release/ui-grid-unstable.js v3.0.0-RC.18-d9b2314 - 2015-01-06 (this version currently available), because pagination refactored since RC.18

**Comment by extdevelopment** [comment] 2015-01-07 23:38
the other component is also necessary, I forgot sry
https://github.com/angular-ui/ng-grid#how-can-i-test-30

**Comment by PaulL1** [comment] 2015-01-08 22:28
Yeah, I'd build from master.  The merge of paging and pagination has broken a few things.  @brianchance may also have some thoughts.

**Comment by brianchance** [comment] 2015-01-08 22:44
I have been testing the  paging and pagination with the latest unstable release, and it has been working fine. Just change the word paging to pagination everywhere.

When I first loaded the new .js file, I did have to clear my cache because I received the pagination not defined.

**Comment by futurechan** [comment] 2015-01-12 16:26
@brianchance did you use bower to install the latest rc?

**Comment by brianchance** [comment] 2015-01-12 16:42
I did not use bower, I grab them off the release site.

**Comment by alexandery** [comment] 2015-01-14 21:30
Pagination styling is broken on IE9. Here are the screenshots from IE9 and FF of one of the tutorial pages:

IE9:
![pagination ie9](https://cloud.githubusercontent.com/assets/3676316/5748021/caf4c6e4-9bf9-11e4-9696-7074c1813bf5.png)

FF:
![pagination ff](https://cloud.githubusercontent.com/assets/3676316/5748028/d636cb6a-9bf9-11e4-9e3f-a9e083696d3a.png)

**Comment by kcaron-cst** [comment] 2015-01-19 19:54
Thanks to the solution posted by @extdevelopment I was able to get pagination in 3.0 RC 18 (bower). Wish I started carousing the github issues a little sooner :)

**Comment by futurechan** [comment] 2015-01-19 21:08
@kcaron-cst what was your bower install command? Last I tried, I got rc16.

**Comment by PaulL1** [comment] 2015-01-19 22:00
@futurechan this might be the reason: #2324

**Comment by kcaron-cst** [comment] 2015-01-19 22:35
@futurechan I had to do a resolution in bower, but in my `bower.json` it looks like:

```
"angular-ui-grid": "3.0.0-RC.18"
```

**Comment by lvarayut** [comment] 2015-02-04 09:18
@kcaron-cst  Did you make it work? I installed `3.0.0-RC.18`. However, It doesn't work for me. :(

**Comment by kencaron** [comment] 2015-02-04 13:21
@lvarayut (I am @kcaron-cst) This is on my todo list to figure out today. I have pagination controls, but requesting a new page just seems to clear the grid without redrawing the data. Are you not seeing the controls even?  My relevant `gridOptions` are:

```
enablePaging  : true,
pagingPageSize: 100
```

& I am using `gridApi.paging.on.pagingChanged` as far as the API is concerned. I'm afraid I will be forced to switch versions to a nightly, which I've been avoiding it due to all the breaking changes, I'd rather deal with them all once RC19 is out.

**Comment by alexandery** [comment] 2015-02-04 17:43
@kencaron If you are using pagination, then your "pagingXXX" settings are not valid. Check the pagination tutorial and adjust your code. It all works fine in that area.

**Comment by kencaron** [comment] 2015-02-04 17:51
@alexandery Thanks, but I was able to figure it out in RC18, which still uses paging. Long story short, my issue stemmed from a misunderstanding of `useExternalPaging` to mean something closer to `enablePaginationControls`

**Comment by alexandery** [comment] 2015-02-04 18:37
@kencaron I guess you are using original RC18 which I moved away from a while ago and had to get everything converted into 'pagination' (which made no sense at all - why rename a feature even if you are re-implementing it?).

**Comment by lvarayut** [comment] 2015-02-05 13:06
@kencaron Pagination doesn't even show up on my page. I don't know what is the cause of the problem. I am using `3.0.0-RC.18` and followed exactly same as  the [tutorial](http://ui-grid.info/docs/#/tutorial/214_pagination).

**Comment by PaulL1** [comment] 2015-02-05 18:37
Try using unstable instead of rc-18

**Comment by kcaron-cst** [comment] 2015-02-05 18:37
@lvarayut Not sure what to suggest other than make a plnkr and make sure all references to `pagination` are `paging` including `ui-grid-paging`/`ui.grid.paging`

**Comment by PaulL1** [comment] 2015-02-05 18:40
If you do as @lvarayut suggests, you'll have to change again with the next rc - the naming has changed to pagination as per the documentation.

**Comment by pmariduena** [comment] 2015-02-06 22:21
@PaulL1 
how do you use bower to download the latest unstable? I just keep getting 3.0.0-rc18. When I tried appending the build number to the bower.json it failed.

bower.json:
```
    "angular-ui-grid": "3.0.0-RC.18-0fa8c48",
```

commands:
```
$ bower cache clean
bower deleted       Cached package angular-ui-grid: C:\Users\me\AppData\Roaming\bower\cache\packages\1fab88ee59631fa775c5f9f5be4692b2\3.0.0-RC.18

me@mymachine  /cygdrive/c/Workspace/projects/TPL/tplServices/branches/testTPL/divrepofitweb/src/main/resources/webapp
$ bower uninstall angular-ui-grid
bower uninstall angular-ui-grid

me@mymachine /cygdrive/c/Workspace/projects/my/myServices/branches/testMy/myAppWeb/src/main/resources/webapp
$ bower install --save-dev
```

Result:
```
bower angular-ui-grid#3.0.0-RC.18-0fa8c48       
not-cached https://github.com/angular-ui/bower-ui-grid.git#3.0.0-RC.18-0fa8c48

bower angular-ui-grid#3.0.0-RC.18-0fa8c48          
resolve https://github.com/angular-ui/bower-ui-grid.git#3.0.0-RC.18-0fa8c48

bower angular-ui-grid#3.0.0-RC.18-0fa8c48     
ENORESTARGET No tag found that was able to satisfy 3.0.0-RC.18-0fa8c48
```

**Comment by kcaron-cst** [comment] 2015-02-06 22:25
@pmariduena `"angular-ui-grid": "https://github.com/angular-ui/ui-grid.info.git#gh-pages"`

**Comment by pmariduena** [comment] 2015-02-06 22:30
@kcaron-cst That didn't work for me. It just loaded a bunch of source code that does not look like what was there before. Can you explain more?

**Comment by kcaron-cst** [comment] 2015-02-06 22:38
@pmariduena Unstable builds via bower is not officially supported as far as I know. See #2276 This method builds off off the demo site's git, which hosts [`release/ui-grid-unstable.js`](https://github.com/angular-ui/ui-grid.info/blob/gh-pages/release/ui-grid-unstable.js)

**Comment by c0bra** [comment] 2015-02-23 23:18
Is this working for everyone with rc.19? Seems like the original issue got derailed with trying to reference unstable.

**Comment by thinkOfaNumber** [comment] 2015-02-26 07:01
I just got it working with rc.20 - check the following three things:

1. load the pagination module `var app = angular.module('app', ['ui.grid', 'ui.grid.pagination']);`
2. add the directive `ui-grid-pagination` as well as `ui-grid="..."`
3. customise grid options `enablePagination`, `enablePaginationControls`, etc.

**Comment by c0bra** [comment] 2015-03-24 16:01
@thinkOfaNumber Thanks for letting me know. I'l go ahead and close this as it appears to be working.

**Closed by c0bra** 2015-03-24 16:01 UTC
Labels: waiting-response

**Comment by dipankarpaul** [comment] 2016-07-25 14:57
I have also faced the UI-Grid Pagination Design issue in IE9. I have resolved this issue with the help of CSS. Follow the below link.... Hope this will help.

[http://dp1981.blogspot.com/2016/07/ui-grid-ie9-pagination-issue.html]

**Comment by deeppatidar** [comment] 2017-02-09 05:05
@extdevelopment I am able to run the external pagination but somehow the new data which I got from api isn't loading proper, I have pagination size [10, 25, 50, 100] its showing correct UI for first 10 record, but once I am selecting 25 the api returning  25 records but  on UI it's showing only 21 records same case with 50 and 100 also.
For this I tried to assign the new record length to ui-grid " $scope.gridOptions.excessRows = $scope.gridOptions.data.length" but still not working.
How can I resolve it .

**Comment by vivek-ealumalai** [comment] 2017-05-12 08:11
hi guys i have 100 row in grid data i'm using useExternalPagination= true and my paginationPageSize= 10  labels in the footer are all showing proper count [1/10  1-10 of 100 items]
but in the grid all 100 rows are rendering in first page itself any  idea where to check ?

**Comment by deeppatidar** [comment] 2017-05-12 08:58
@vivek-ealumalai Have you define pagination option and record per page in gridOption object.
 gridOptions {
            paginationPageSizes : [10, 20, 50, 100],
            paginationPageSize : 10,
    }

**Comment by vivek-ealumalai** [comment] 2017-05-13 08:08
@deeppatidar Yeah! please find below my grid-option properties (i'm assigning through variables though)
gridOptions {
paginationPageSizes : [10, 25, 50, 75 ,100],
paginationPageSize : 10,
}
