### ISSUE TITLE
afterCellEdit event always fired twice, once on edit and once on scroll

### ISSUE THREAD

**Issue by ankit5990** [angular-ui/ng-grid#1746] opened 2014-10-07 13:34 UTC
afterCellEdit event is always being fired twice.
Once when actual editing of a cell is done, and other when a scroll is done on the grid.

When doing a server side save, this is leading to useless AJAX calls.

Made a plunk to show the issue.
1. select gender from the dropdown.
2. an alert shows afterCellEdit event.
3. scroll on the grid.
4. An alert is again seen for afterCellEdit event.

http://embed.plnkr.co/UZjzKbFqd4pLkc35zrzE/preview

**Comment by mtlehtin** [comment] 2015-01-21 06:51
I'm having the same issue. Seems that after flushing the dirty rows and then scrolling the grid, they are dirty again.

Can be reproduced with this plunker (90% of the times):
1. Change the gender cell value male -> female
2. Flush dirty (dirty rows are shown until promise is resolved). Grid seems to be ok
3. Then scroll the grid. Same row is still dirty
4. Flush dirty again, wait until promise is resolved
5. The grid is clean.

http://plnkr.co/edit/DdMGLf9b23XKRGNHGgpu?p=preview

**Comment by PaulL1** [comment] 2015-01-21 07:40
OK, from debugging through the code, it looks like we register a listener for ending cell edit, and another for grid scroll.  When we end cell edit we don't deregister the scroll listener, so when we scroll it still fires.  We need to deregister both listeners when either are triggered.  I'll do an update.

**Comment by PaulL1** [comment] 2015-01-21 08:20
Closed in #2600

**Closed by PaulL1** 2015-01-21 08:20 UTC
Labels: bug, duplicate

**Comment by mtlehtin** [comment] 2015-01-21 08:51
Thanks a lot!

**Comment by piyush21upadhyay** [comment] 2020-06-01 14:26
Hi,

We are using the editable grid where user can navigate the cells through tabs also and edit the cell. Things work as expected till we have horizontal scroll either not present on the screen OR scroller has not been moved right from its initial zero position.

Ex: say while tabbing till cell 6 horizontal scrollers remains stable, so till that cell user can tab, focus and edit the cell. The moment we move to cell 7 and scroller moves forward, user can tab to cell 7, focus works on cell 7 too but cell becomes non editable, reason being the call to _afterCellEdit_ event from deregOnGridScroll function present in ui-grid-edit.js. 
User can surely edit the cell by clicking on it OR scrolling the horizontal bar, but it goes against the tabbing/focusing/editing feature of ui-grid and defeats the purpose.
Could you guys help me here, so that user can keep on editing the cell from 1st column till the last one by tabbing through cells with scroller moving forward?
