### ISSUE TITLE
ngTemplates.removeAttributeQuotes during build causes error in interpolated attributes

### ISSUE THREAD

**Issue by MagicIndustries** [angular-ui/ng-grid#3427] opened 2015-05-06 05:44 UTC
Took me a while to track this down but I found the dist version of my app showed this error on the grid:

    Error: Failed to execute 'setAttribute' on 'Element': 'col)}}' is not a valid attribute name.

I tracked it down to a cellTemplate that used a directive, passing {{COL_FIELD}} into an attribute. I tried stable and unstable, and modified the extra modules I was using, but the only thing that made a difference was removing the use of the directive. 

The cell template I was using in the grid looks like this:

    <div class="ui-grid-cell-contents text-center">
        <dms-file-type-icon file-type="{{COL_FIELD}}"></dms-file-type-icon>
    </div>

The directive in question is simple and has an external template:

    (function () {
        'use strict';
        angular.module( 'dms.webui.document')
            .directive( 'dmsFileTypeIcon', function () {
                return {
                    scope: {
                        fileType: '@'
                    },
                    replace: true,
                    restrict: 'E',
                    controller: function ( $scope, Labels, Util ) {
                        $scope.labels = Labels.get( 'labels.dmsFileTypeIcon');
                        var fileStrings = Util.getFileStrings( $scope.fileType );
                        $scope.iconClass = fileStrings.iconClass;
                        $scope.altTag = fileStrings.altTag;
                    },
                    templateUrl: 'app/document/directives/dmsFileTypeIcon.html'
                };
            });
    })();

the directive template itself looks like this:

    <i class="fa {{iconClass}}" alt="{{altTag}}" tooltip="{{altTag}}" tooltip-placement="right"></i>

What fixed the issue for me was changing one of the options in the ngTemplates config in my Gruntfile.js. I changed removeAttributeQuotes to false, and no longer receive the error. 

I don't know whether the fault is in ngTemplates or if there's some specific condition in the ui-grid code, but changing that flag is is definitely what fixed the error for me.

**Comment by PaulL1** [comment] 2015-05-16 02:47
Hmm.  The code does a replace on COL_FIELD `.replace(uiGridConstants.COL_FIELD, 'grid.getCellValue(row, col)');` in ui-grid-cell.js.

I don't really see why that would give you this problem, but it looks like that's what's breaking.  You could put a breakpoint on that line (line 36 of ui-grid-cell.js in my version) and see what's in $scope.col.cellTemplate, and why that replace would cause things to break.  I suspect as you suggest that the problem is ngTemplates, but it's worth checking.

**Comment by PaulL1** [comment] 2015-06-06 01:08
Solution provided that may resolve this issue, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.

**Closed by PaulL1** 2015-06-06 01:08 UTC
Labels: waiting-response

**Comment by yadimon** [comment] 2017-01-27 10:50
to the problem: ngTempaltes removeAttributeQuotes removes quotes if possible. e.g. <div title="{{COL_FIELD}}">{{COL_FIELD}}</div> the part with `title` attribute, will be compressed by ngTemplates to `title={{COL_FIELD}}`, because there are not spaces in `COL_FIELD`, but later, after it will be replaced by uigrid, it will be `title={{grid.getCellValue(row, col)}}` and that is not valid value, because there are spaces, so html takes only part as value `title={{grid.getCellValue(row,`
i think such hard replace is not the best solution. At least the space after comma should be removed, to keep the replaced value working, even without quotations.
