### ISSUE TITLE
Sort by clicking column header is broken on touch-enabled Windows device

### ISSUE THREAD

**Issue by AgDude** [angular-ui/ng-grid#2616] opened 2015-01-23 13:12 UTC
I observed this in my own project, as well as in the tutorial here: http://ui-grid.info/docs/#/tutorial/102_sorting

I can sort by using the column menu, but not by clicking on the header. I am using Windows 8.1 and Chrome 40.

**Comment by jpuri** [comment] 2015-01-23 14:31
It works for me in the tutorial link you shared above except if column has:
enableSorting: false 

I checked in chrome version 40.0.2214.91.

**Comment by AgDude** [comment] 2015-01-23 15:19
I can confirm that this issue does not occur on Linux Chrome 34. On windows I am using the same version of chrome as @jpuri. I suspect this is related to #2550. 

I have windows 8.1, running on a laptop with touch support. I am not using the touchscreen (connected to external monitors), but I wonder if this is a bug in how chrome is detecting a "touch" device...

**Comment by PaulL1** [comment] 2015-01-25 01:54
@AgDude: that sounds like a reasonable supposition.  But unfortunately I don't have a touch enabled windows machine to check.  Are you able to put some breakpoints in the code and find out what sort of event (if any) is being fired when you click on the column header?

I'd suggest in ui-grid-header, around about the lines that show:
```
            if ($scope.sortable || $scope.colMenu) {
              // Long-click (for mobile)
              var cancelMousedownTimeout;
              var mousedownStartTime = 0;
```

Looking at the code, I suspect you're right on your diagnosis, because it does:
```
              var downEvent = gridUtil.isTouchEnabled() ? 'touchstart' : 'mousedown';
              $contentsElm.on(downEvent, function(event) {
```
And I'm guessing that the event you're getting is a mousedown, but because your device is touch enabled we're waiting on a touchstart.

I wonder what would happen if we always just waited on both.....what harm that would cause.

**Comment by AgDude** [comment] 2015-01-26 12:00
You are correct about the events. ```downEvent``` evaluates as "touchstart", but since I am using a mouse it would never occur. I don't see any harm in listening for both.

**Comment by c0bra** [comment] 2015-01-29 22:29
I've changed the title to clarify the issue.  Unfortunately listening to both can be problematic because BOTH events will fire during a touch/click sequence, causing extra event handling and breaking stuff.

I don't have a Windows touch device to test with. @AgDude Do you know if there's any way to do emulation, maybe in IE11?

**Comment by AgDude** [comment] 2015-01-29 23:05
@c0bra Chrome has emulation mode, it is in a tab next to the console. The bottom option is a "touch notebook". I  can't verify it will work, since I am on a touch laptop at the moment.

**Comment by c0bra** [comment] 2015-01-30 22:07
Yea I know about Chrome's emulation. I guess I'd like to test with a device that has both touch and mouse capabilities at once, so I could reproduce the behavior you're getting.

**Comment by AgDude** [comment] 2015-01-30 22:40
I haven't looked closely at the code, to see how this would fit, but here is my suggestion on how to handle this. 

When the app first loads, use the current method to guess if this is a touch device, and cache that value somewhere.
If it is touch enabled, listen for any mouse event (probably even ```mousemove```) , and as soon as you get a mouse event, overwrite that cache, calling this a mouse device (and remove the listener).

**Comment by c0bra** [comment] 2015-01-30 22:47
I know I've ran into problems where some environments are firing both types of events, you can see my commit that adding disparate touch/mouse handling here: https://github.com/angular-ui/ng-grid/commit/995d3c472530407d19124e622c570fa65319e6fb

If there's a way forward that will allow both them I'm all for it, but I think we're going to be constrained if we're listening for both and both types will fire for the same touch sequence.

**Comment by AgDude** [comment] 2015-01-30 23:31
I looked through your code some, and also at the source for hammer.js. According to the comments there, touch devices will fire the touch event before the mouse event.  So the way hammer works is that while a touch event is active, a mouse event can't start. 

The code I am referring to is here: 
https://github.com/hammerjs/hammer.js/blob/master/src/input/touchmouse.js


In the case of  ```downEvent``` You could use the ```cancelMouseDownTimeout``` promise, adding a ```isTouch``` property just after it is assigned.  

On the ```upEvent``` I think you are save listening to both, since it just cancels the timer.

I don't see a good solution to the case of ```clickEvent```, without adding another timer. Could we listen for both events, and not accept the opposite event for some time (say 500ms)? That seems a bit hacky, but it might work.

**Comment by AgDude** [comment] 2015-01-31 12:17
This link has a list of the order in which these events are supposed to fire.
http://www.html5rocks.com/en/mobile/touchandmouse/#toc-together

**Comment by c0bra** [comment] 2015-02-06 19:38
Thanks for the info, @AgDude. This is on my radar and I hope to take a look at testing some changes along these lines.

**Comment by AgDude** [comment] 2015-02-24 13:02
I spent some time working on this yesterday, and the approach I was using with a "active" touch event was ineffective. ```touchstart```and ```touchend``` may both fire before the emulated mouse events, meaning that a timer is really needed.

Also a word of warning, you will find many references that ```event.preventDefault``` will stop the emulated mouse events, but this won't work on some android stock browsers.

**Comment by c0bra** [comment] 2015-03-11 15:42
Note: I can't reproduce the problem with "Notebook with touch" emulation.

**Comment by PaulL1** [comment] 2015-03-15 07:26
A possible approach to a solution has been provided on #2550, if that works then I think we can code a similar solution here.

**Comment by c0bra** [comment] 2015-03-16 15:09
@AgDude After quite a bit of time I got Windows 8 set up on a VM and ran the simulator  from VS 2013 so I could test touch events. I found that our `isTouchEnabled` method returns false in this instance.  Could you try it on your machine just to see:

```javascript
(('ontouchstart' in $window) || $window.DocumentTouch && $document instanceof DocumentTouch)
```

**Comment by AgDude** [comment] 2015-03-16 15:28
@c0bra if you are using chrome, try ```chrome://flags/ ```, ```enable touch events```
source: https://productforums.google.com/forum/#!topic/chrome/P1w9dhH_874

I disabled touch events on my development machine, but it should allow you to enable touch events on a machine without a touchscreen.

**Comment by c0bra** [comment] 2015-03-24 18:15
@AgDude ah-ha! That breaks it for me!  OK now I can work on fixing it :)

Thanks!

**Comment by PaulL1** [comment] 2015-03-24 20:38
@c0bra: take a look also at my touch branch, which is based on what the hammer guys do.  They basically enable events for both touch and mouse, but once the touchstart/mousedown happens (whichever happens first) they disable the other.  So they don't get problems with duplicate events.  At the end of that event (i.e. touchend/mouseup), then they enable both handlers again.

**Comment by AgDude** [comment] 2015-03-24 20:50
@PaulL1, your description is not quite correct. I implemented what you describe, and discovered in broke iOS an Android devices (and I never found the time to improve on it)

@c0bra, You need to include a "debounce" or delay in addition to what @PaulL1 describes. It is possible that the sequence of events will be touchstart, touchend, mousedown, mouseup, since emulated mouse events often have a delay (typically 300ms).

**Comment by PaulL1** [comment] 2015-03-24 20:53
And the branch I provided also breaks iOS, and it's on my list to try it out on my iPad and work out why.  But apparently it is "better" than what we had previously, and I think it's the start of having it working in a more consistent way.

**Comment by PaulL1** [comment] 2015-03-28 03:57
@AgDude, as with a couple of other similar issues, do you want to look at #3142 to see if it addresses this?

**Comment by PaulL1** [comment] 2015-04-01 03:00
I think this is resolved, closing.

**Closed by PaulL1** 2015-04-01 03:00 UTC
Labels: Hi-Pri Bug, waiting-response

**Comment by remoe** [comment] 2015-08-22 11:30
Thanks for this transcript. It was helped me a lot to fix the same bug on another system ;)
