### ISSUE TITLE
Infinite scroll needLoadMoreDataTop works weird (or how should that work)

### ISSUE THREAD

**Issue by jcompagner** [angular-ui/ng-grid#3059] opened 2015-03-19 13:32 UTC
first if you go to the example:

http://ui-grid.info/docs/#/tutorial/212_infinite_scroll

and you do 1 click down, (so scroll only 1 row)
then 1 up again you see suddenly a completely different list. This is quite weird and brings to my question how shoiuld needLoadMoreDataTop really work?

Because if you start from the top then all the data is already there on the top.. Its not that suddenly you need to fill a row thats on a negative index 

Or is this feature for that if you would start somewhere in the middle? in the first place? But then the start is just wrong, because you first have to scroll a bit down to be able to fill it up. thats just bad ui.

besides that you need to really supply neadLoadMoreDataTop because if you don't do that:

http://plnkr.co/edit/56DNHGw1FHQFF5HtpGhL?p=preview

then if you click once down, then one time up (so that it would have triggered dataTop once) then suddenly the whole needLoadMore is broken because the timeout stays on true...

so i need to always add a dummy function that just does:

  gridApi.infiniteScroll.on.needLoadMoreDataTop($scope,function(){
			    	$scope.gridApi.infiniteScroll.dataLoaded();
				});

because that will set the:  grid.options.loadTimout = false; 

so it works the next time i scroll. But again i have no idea what to really do in that method otherwise.

If infinite scroll would really be some kind of "page" so that the needMoreData (top) did get more arguments so i know exactly what the view port should be (or become)
then i could delete rows at the top and cleanup my stuff
Then needMoreDatatop would load that data back in. 
Problem is that then the scrollbar will not work i guess because for a ui-grid point of view if i would delete data on the top the total rows would just be smaller.

**Comment by PaulL1** [comment] 2015-03-26 05:32
I made some substantial changes to infinite scroll the other day that should probably address this.  They're committed to master, but don't appear to have come through to the tutorials and unstable.  You could perhaps check out master and see whether they resolve this issue.

**Comment by PaulL1** [comment] 2015-03-28 22:36
These changes are now in the tutorial.

**Comment by jcompagner** [comment] 2015-03-30 10:03
i am testing the tutorials and yes it works now way better and more natural (still a bit weird but at least you can now click directly that you want to go up and it goes up then)

But i guess for people that want to start "in the middle" you can do that now.

the thing that is still "broken" in my eyes is that if you disable (in the infinite scroll example)

/gridApi.infiniteScroll.on.needLoadMoreDataTop($scope, $scope.getDataUp);

that line so you don't configure needLoadMoreDataTop (because i am really not interessted to that)
then scroll down also breaks if you scrolled up once..

**Comment by PaulL1** [comment] 2015-03-30 15:31
If you don't want to scroll up, then you would now set gridOptions.infiniteScrollUp to false.

**Comment by jcompagner** [comment] 2015-03-30 15:53
but that isn't default somehow?

http://plnkr.co/edit/0GkLNV8QczMVja7NzxfC?p=preview

i deleted that gridOptions.infiniteScrollUp : true line and the needLoadMoreDataTop
but still that breaks scrolling.

why do we have now those properties? because what happens if i don't specify the infiniteScrollDown but i do specify the  gridApi.infiniteScroll.on.needLoadMoreData($scope, $scope.getDataDown);

or the other way around?

this should in my eyes just be 1 thing. that property can be set when needLoadMoreData is called.

**Comment by PaulL1** [comment] 2015-04-21 08:29
That plunker doesn't run.

The issue is that if you delete the infiniteScrollUp, you also need to always provide false to that parameter in the dataLoaded call.  If you leave those calls alone, then next time you provide data down, it will re-enable the scroll up.

**Comment by jcompagner** [comment] 2015-04-21 08:40
weird that the plunker doesn't run, for me it runs fine

http://plnkr.co/edit/0GkLNV8QczMVja7NzxfC?p=preview

the thing i am trying to say is that we have no 2 booleans or configuration options that you have to use both and they have to be in sync.

if i use the plunker and i scroll down then that works fine
but if i have scrolled up once (completely to the top) and then down again then it is broken

the plunker is just this: http://ui-grid.info/docs/#/tutorial/212_infinite_scroll

but then 2 lines deleted: 

 infiniteScrollUp: true,
 gridApi.infiniteScroll.on.needLoadMoreDataTop($scope, $scope.getDataUp);

in the code

then it just breaks, but i don't want scrollUP i don't want to be forced to configured it or call it.

**Comment by PaulL1** [comment] 2015-04-21 08:45
If you leave it out, then you need to:
1.  when you call `dataLoaded` you always provide false to the scrollUp property
2.  remove the logic that deletes spare pages of data - that logic will re-enable scrollUp

Refer http://plnkr.co/edit/0GkLNV8QczMVja7NzxfC?p=preview

**Comment by TizeShrey** [comment] 2015-04-21 10:40
Refer http://plnkr.co/edit/0GkLNV8QczMVja7NzxfC?p=preview
This plnkr won't pull records on getDataDown. Since you have removed infiniteScrollUp, it's supposed to work downwards or am I missing something ?

**Comment by jcompagner** [comment] 2015-04-21 11:09
ok i see now http://plnkr.co/edit/0GkLNV8QczMVja7NzxfC?p=preview

i removed all the firstPage > 0 checks to be just false.

Then it seems working (but in our own thing where we never give those values its was broken, i needed to really configure it)

but still don't you agree that it is still a bit weird api?

we have this as a config option:

infiniteScrollUp: true,

if i make that:

infiniteScrollUp: false,

(or remove it)

then suddenly the dataloaded method overrides that completely again?

that just doesn't seem logical to me, because we have currently 3 things..

1> the property: infiniteScrollUp
2> the register method: gridApi.infiniteScroll.on.needLoadMoreDataTop($scope, $scope.getDataUp);
3> the dataloaded call: $scope.gridApi.infiniteScroll.dataLoaded($scope.firstPage > 0, $scope.lastPage < 4).

and they all work a bit together but also not fully, they also override each other..

i get the last one, is there more.. but if we have then that infiniteScollUp property that is false then true should just not do anything. because that is the configuration..

But do we need infiniteScrollUp in the first place? Can't we just trigger/set this when we see the register method (point 2)?
because what does point 2 do if i have the property on false?
or visa versa what does the property true mean if i don't register?

**Comment by PaulL1** [comment] 2015-04-21 19:41
Infinite scroll up was specifically requested by someone who submitted a PR to implement it.  So I think we do need it - some people start scrolling in the middle of a list for any of a variety of reasons.

The loadData method is directly setting the infiniteScrollUp and infiniteScrollDown flags, so they aren't different things.  If you tell the grid there's data up, then it will allow scroll up.

**Comment by PaulL1** [comment] 2015-05-25 23:52
Closing, no further commentary for 1 month, and I think this is working as intended.

**Closed by PaulL1** 2015-05-25 23:52 UTC
Labels: waiting-response
