### ISSUE TITLE
ui-grid sorting icons are missing when refresh page on IE

### ISSUE THREAD

**Issue by sarbjeet65** [angular-ui/ng-grid#3376] opened 2015-04-28 20:02 UTC
Hi,

The ui-grid sorting icons are displaying correctly when page first loaded. When this page is refresh using F5 on IE11, then Chinese icons starts appearing. This is working fine in other browsers such as Chrome and Firefox.

Thanks,

**Comment by c0bra** [comment] 2015-04-28 21:17
"Chinese" icons mean that the font isn't loading properly. Check your network tab in IE developer tools and make sure they're not being cached weirdly, and make sure your cache is clear to start. IE has a lot of caching idiosyncrasies that I've ran into, even in IE11.

**Comment by sarbjeet65** [comment] 2015-04-29 16:54
Thanks,

I have cleared browser cache and verified on network tab, the fonts are loading getting 200 status code. Still on page the "Chinese" icons are appearing when page is refresh using F5.

**Comment by sarbjeet65** [comment] 2015-04-29 19:49
I just want to provide you more details in terms of environment. I am using Tomcat 6 and accessing webpage using HTTPS protocol.

**Comment by PaulL1** [comment] 2015-05-16 00:01
FYI, apparently the icons are Korean.  The cause is almost certainly that the font isn't being recognised, as this is the same behaviour we get if we don't include the font at all.  Could you look at http://ui-grid.info/docs/#/tutorial/116_fonts_and_installation and consider whether anything in there could be impacting.  Does IE11 have some way to tell what exactly it's doing with the font - is there some debug statement or other tool that will tell you why it's not using the font that's provided?  (Sorry, not very good with IE11 myself, and don't have a copy of it to test on)

**Comment by PaulL1** [comment] 2015-06-06 01:06
Solution provided that may resolve it, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.

**Closed by PaulL1** 2015-06-06 01:06 UTC
Labels: waiting-response
