### ISSUE TITLE
Disable Row

### ISSUE THREAD

**Issue by lecoleco** [angular-ui/ng-grid#3103] opened 2015-03-24 23:56 UTC
Hi,
Have another way to disable a row? 
This not work on my application.

$scope.disableFirstRow = function() {
      $scope.gridApi.selection.clearSelectedRows();
      $scope.gridOptions.enableRowSelection = !$scope.gridOptions.enableRowSelection;
      $scope.gridApi.core.notifyDataChange( uiGridConstants.dataChange.OPTIONS);      
  };

I try to make the same problem on plucker but not have success.
http://plnkr.co/edit/Iu4gbqWno4UrIJi2kVRn?p=info

Thank you

**Comment by PaulL1** [comment] 2015-03-25 00:20
If it works on plunker but doesn't work in your application, then you need to go through a process of looking at everything that is different in your application and plunker, and then determining which of those differences is resulting in the different behaviour.

Common culprits would include:

- version.  Are you using rc20 or unstable.  Are there changes in this area?  Try putting rc20 into the plunker to see if that makes the plunker break
- extra code between your plunker and your application.  Add more logic to more closely replicate your application until the plunker also starts having the issue
- timing issues.  Often the problem is that the plunker loads data or defines column defs at a different time than your code - so pay close attention to the order that things are happening in.

**Comment by lecoleco** [comment] 2015-03-25 13:32
Hi, i use rc20 on both and no change.

My application use many plugging and use requerijs.

The controller is define on router, after click on menu the grid start and define columns and load the data.
I put the plunker and my application closely.

I think the problem is on the controller.

This is my controller..

(function( define ) {

    "use strict";

    define( [],

        function(buildTimeString) {


            var COLUMNS_GRID = [
                { displayName: 'Status despesa',    field: 'status_despesa',                enableFiltering: false, enableColumnMenu: false, width:'20%' },
                { displayName: 'Colaborador',       field: 'fk_id_colaborador',             enableFiltering: false, enableColumnMenu: false, width:'20%' },
                { displayName: 'Aprovador',         field: 'fk_id_colaborador_aprovador',   enableFiltering: false, enableColumnMenu: false, width:'20%' },
                { displayName: 'Valor despesa',     field: 'total_despesa',                 enableFiltering: false, enableColumnMenu: false, width:'15%', cellFilter: 'currency:"R$ "', filter:false },
                { displayName: 'Valor aprovado',    field: 'total_aprovado',                enableFiltering: false, enableColumnMenu: false, width:'15%', cellFilter: 'currency:"R$ "', filter:false },
                { displayName: 'Valor rejeitado',   field: 'total_rejeitado',               enableFiltering: false, enableColumnMenu: false, width:'15%', cellFilter: 'currency:"R$ "', filter:false },
                { displayName: 'Data solicitação',  field: 'data_solicitacao',              enableFiltering: false, enableColumnMenu: false, width:'15%', cellFilter: "date:'dd/MM/yyyy'" },
                { displayName: 'Hora solicitação',  field: 'hora_solicitacao',              enableFiltering: false, enableColumnMenu: false, width:'15%' },
                { displayName: 'Data analise',      field: 'data_analise',                  enableFiltering: false, enableColumnMenu: false, width:'15%', cellFilter: "date:'dd/MM/yyyy'" },
                { displayName: 'Hora analise',      field: 'hora_analise',                  enableFiltering: false, enableColumnMenu: false, width:'15%' },
                { displayName: 'Data pagamento',    field: 'data_pagamento',                enableFiltering: false, enableColumnMenu: false, width:'15%', cellFilter: "date:'dd/MM/yyyy'" },
            ];

            var ConsultaMovimentacaoControle = function( sessao, reembolsoServico, modalServico, $scope, $q, i18nService, $timeout, toastr, $rootScope ) {


                i18nService.setCurrentLang('pt-br');

                var loadData = function() {

                    //servico
                    return reembolsoServico

                        .getDataBD( $scope.formulario )

                        .then(
                            function onResult( response ) {

                                $scope.gridApi.selection.clearSelectedRows();
                                $scope.gridOptions.data = response.data.result;

                                if ( $scope.gridOptions.data === null ) {
                                    $scope.gridOptions.data = [];
                                }

                            },
                            function onFault( fault ) {

                                errorMessage( fault );

                                return $q.reject( fault );
                            }
                    );

                };



                var onDefineGrid = function(load) {

                    var sql   = "";

                    $scope.columns                  = COLUMNS_GRID;

                    $scope.gridOptions = {

                        enablePaginationControls: false,
                        modifierKeysToMultiSelect: true,
                        enableSorting: true,
                        enableFiltering: true,
                        multiSelect: true,
                        enableRowHeaderSelection:false,
                        enableRowSelection: true,
                        enableSelectAll:true,
                        showGridFooter : false,
                        paginationPageSize: $scope.formulario.itensPagina,
                        columnDefs: $scope.columns,

                        onRegisterApi: function (gridApi) {

                            $scope.gridApi = gridApi;

                            gridApi.selection.on.rowSelectionChanged($scope, function (row) {

                                //verifica se todos as linhas foram selecionadas e ativa o btn selecionar todos

                                $scope.selecionaTodos     = ( gridApi.grid.options.totalItems === gridApi.selection.getSelectedRows().length );
                                $scope.disableBtnConsulta = ( gridApi.selection.getSelectedRows().length === 0 );

                                $scope.disableBtnAprovacao      = ( findDataByColaboradorDesc(row.entity.fk_id_colaborador) !== sessao.conta.id );
                                $scope.disableBtnStatusDespesa  = $scope.disableBtnAprovacao;

                                if ( !$scope.disableBtnAprovacao ) {
                                    $scope.disableBtnAprovacao = ( row.entity.status_despesa !== TYPE_STATUS_DESPESA[0]['name'] );
                                }

                                if ( !$scope.disableBtnStatusDespesa ) {
                                    $scope.disableBtnStatusDespesa = ( row.entity.status_despesa !== TYPE_STATUS_DESPESA[1]['name'] );
                                }

                            });
                        }
                    };

                    if (load) {

                        //here cames a query

                        loadData();

                    } else {
                        $scope.gridOptions.data = [];
                    }
                };

                onDefineGrid(false);

            };

            return [ "sessao", "reembolsoServico", "modalServico", "$scope", "$q", "i18nService", "$timeout", "toastr", "$rootScope", ConsultaMovimentacaoControle ];
        }
    );

}( define ));

**Comment by PaulL1** [comment] 2015-04-12 06:35
I think we need a plunker to help you resolve this.  If it's not happening in plunker, and it is happening in your application, then you need to add things from your application to the plunker until the plunker breaks, or the plunker looks exactly like your application.

**Comment by PaulL1** [comment] 2015-05-15 19:36
Closing, no further information forthcoming for one month.

**Closed by PaulL1** 2015-05-15 19:36 UTC
Labels: waiting-response
