### ISSUE TITLE
Resize Columns in Chrome on Windows 8 (touch-enabled) not working

### ISSUE THREAD

**Issue by jaskaye17** [angular-ui/ng-grid#2550] opened 2015-01-14 19:25 UTC
There appears to be an issue re-sizing the column widths using the ui-grid-resize-columns directive in Chrome. The functionality appears to work fine in IE and Firefox. I expect the column width to readjust on drag; however, nothing  happens in Chrome when I try to drag with the 'drag icon'. This can be seen at the following plnkr:

http://plnkr.co/edit/iC3IKKVOVoPoX9T9qOXV?p=preview

This may have a relation to a separate issue that I have noticed with ui-grid-move-columns directive not working properly in Chrome, but, working in Firefox and IE. The issue can also be seen in the above plnkr. A recent bug issue was filed and resolved which appeared to address this issue. I am still; however, noticing the problem described above #2354.

**Comment by PaulL1** [comment] 2015-01-14 19:37
It's working for me in Chrome on the tutorial: http://ui-grid.info/docs/#/tutorial/204_column_resizing

Resize is also working for me with your plunker.  What version of Chrome, and what OS are you using?

**Comment by jaskaye17** [comment] 2015-01-14 20:11
Hey @PaulL1 Thanks for the prompt response!

I am using Chrome: Version 39.0.2171.99 m and windows: Version 8.1 Pro

**Comment by PaulL1** [comment] 2015-01-14 20:48
And are you also getting this problem on the tutorial pages, or only in the plunker?  I have 39.0.2171.95 (64-bit), but on OSX.  I wouldn't expect that to make a difference, but I see Chrome is currently updating itself, so maybe when that finishes I'll have .99 and it might break.

**Comment by PaulL1** [comment] 2015-01-14 21:03
Are you using expandable?  I see issue #2277, which may be related.

**Comment by jaskaye17** [comment] 2015-01-14 21:07
I am having the same problem directly from the tutorial page as well as from the plunker. In this demo/test I am not using expandable; just what is in the demo and plunker without any tinkering. Very strange. My coworker, who also has the same computer setup/dev environment, has the same issue using the feature in chrome.

**Comment by cmaxo** [comment] 2015-01-19 16:21
I have the same issue. If I run Firefox it totally works. My chrome version is 39.0.2171.99 m on windows pro 8.1.

**Comment by AgDude** [comment] 2015-01-23 12:33
I can confirm this on windows 8.1 Chrome Version 40.0.2214.91 

It is working fine on Ubuntu with Chrome Version 34.0.1847.116

I have observed this on the 204 tutorial page.

**Comment by c0bra** [comment] 2015-02-06 19:40
This does indeed seem to be the same issue as #2616. Touch-enabled devices that also have mouse-style inputs aren't getting events correctly.

**Comment by jaskaye17** [comment] 2015-02-26 17:13
Has there been any further development with this?

**Comment by jaskaye17** [comment] 2015-02-27 01:00
The issue does appear to be column resizing in chrome on windows 8 (touch-enabled is working) this is because the code registers 'down events' as 'touchstart' when istouchenabled is detected as true. Clearly this is not ideal when using 8.1 touch enabled. 

I have created a fix for this by always registering click events and then additionally registering touch events when touch is detected. This has worked for my needs, however it has not been tested across all devices. I have [read](http://www.stucox.com/blog/you-cant-detect-a-touchscreen/) that one 'should assume anyone may have a touch screen for events and interactions' and therefore my strategy seems  to make sense. However, in #2616 @c0bra makes a comment 'Unfortunately listening to both can be problematic because BOTH events will fire during a touch/click sequence, causing extra event handling and breaking stuff'.

Before I make a PR with my solution, I'd like to see if there are any thoughts on this approach.

**Comment by AgDude** [comment] 2015-02-27 11:54
@jaskaye17 listening to both events will not work on iOS devices and many android devices. They emit both the touch events and what are known as "emulated mouse events." In the case where you are listening for down/up events separately, it might appear to work, but you end up with each handler executing twice. In a situation where you are listening for touch/click (for example column sorting), it won't work, because you sort once with the touchstart event, then 300ms later reverse the sort with the emulated click event.

We need to put together a more robust system than listening for both. If you have time to commit to a fix, I am willing to do some validation on various devices for you. If you want a starting point, look at the source for hammer.js. That library is overkill for what we need here, but it is widely used and works very well.

**Comment by jaskaye17** [comment] 2015-02-27 17:15
@AgDude Thanks for the explanation. I was not aware of that, but, clearly it is good information to know. I'll have a look at hammer.js and see what I can come up with.

**Comment by PaulL1** [comment] 2015-03-15 06:42
I think we need to include hammer.js purely because of the awesomeness of their examples:

```
var hammertime = new Hammer(myElement, myOptions);
hammertime.on('pan', function(ev) {
    console.log(ev);
});
```

 (not to mention the linked loop).

**Comment by PaulL1** [comment] 2015-03-15 06:55
From reviewing the code, the approach they take is to have handlers for both mouse and touch events, but once you start a touch event they disable the mouse events for a period:
  https://github.com/hammerjs/hammer.js/blob/master/src/input/touchmouse.js

So really it looks to be just a debounce of sorts - they seem to rely on the touch events always firing first, and once a touch event fires they set a timer and don't process mouse events for that period.  The logic is presumably that you can't get your hand from the screen to the mouse faster than 500ms or so.  Which seems reasonable to me.

They're actually doing it by detecting an event end, and then resetting the handler.  Which I guess means that they've got a mouseDown or touchDown, and you ignore other types of input until you have a mouseUp or touchUp.  And I guess if you get a mouseUp after you've already had a touchUp, it won't hurt anything.

I may look at a PR that tries this, and then ask @jaskaye17 to try that on his device.

**Comment by PaulL1** [comment] 2015-03-15 07:25
@agdude, @jaskaye17: could I ask you to check out and try this branch to see if resizing works properly on your touch device?  If it does then we can probably apply this approach to all the touchdown/touchup type events.

**Comment by AgDude** [comment] 2015-03-16 15:20
Thanks @PaulL1 for working on this. I have a busy week, but I will try to find time to validate this sometime in the next few days.

**Comment by PaulL1** [comment] 2015-03-28 03:56
@jaskaye17, @AgDude: I think #3142 will address this, would you be able to check it out and see if it resolves it for you?

**Comment by c0bra** [comment] 2015-03-30 16:05
It's looking good to me!

**Comment by PaulL1** [comment] 2015-04-01 03:01
I think this is resolved, closing.

**Closed by PaulL1** 2015-04-01 03:01 UTC
Labels: Hi-Pri Bug, waiting-response
