### ISSUE TITLE
Scroll up doesn't work for full height grid 

### ISSUE THREAD

**Issue by rupampatel2006** [angular-ui/ng-grid#3566] opened 2015-05-22 17:17 UTC
Hello, 

If height of grid is set such that vertical scroll is not needed, Scrolling down works as expected but Scroll up is doesn't work at all. 

Plnkr: http://plnkr.co/edit/QveBjYZkMD6NK59zuiXS?p=preview

**Comment by tuhoojabotti** [comment] 2015-05-26 07:18
Duplicate of #3340?

**Comment by Jacquelin** [comment] 2015-05-26 12:30
Yes, it's the same but for me

**Comment by PaulL1** [comment] 2015-05-26 19:57
OK, closing then.

**Closed by PaulL1** 2015-05-26 19:57 UTC
