### ISSUE TITLE
UI-Grid Web and Keyboard Accessible 

### ISSUE THREAD

**Issue by rajulkansara** [angular-ui/ng-grid#3038] opened 2015-03-17 20:16 UTC
I tried to find out resources to make grid web and keyboard accessible. It would be great to hear from owners about the same.

**Comment by PaulL1** [comment] 2015-03-17 21:07
Duplicate of #2840.  Short answer, we'd love it but nobody is currently working on it.  We're keen to provide support to someone who wants to contribute this work though - in concept it shouldn't be hard.

**Closed by PaulL1** 2015-03-17 21:07 UTC
