### ISSUE TITLE
Toggle filter

### ISSUE THREAD

**Issue by samhenri** [angular-ui/ng-grid#1929] opened 2014-10-27 14:36 UTC
I was following the tutorials and found this one: http://ui-grid.info/docs/#/tutorial/105_footer

Is it possible to toogle filtering options just like the footer on this tutorial section? I've forked a Plunker to test it but it doesn't work: http://plnkr.co/edit/kQgpiHXbnJlklQOHzc3Z?p=preview

**Comment by PaulL1** [comment] 2015-01-14 22:29
Duplicate of #2067

**Closed by PaulL1** 2015-01-14 22:29 UTC
Labels: enhancement

**Comment by ssonnenwald** [comment] 2015-03-18 12:50
Hi Paul,
    I know yesterday you indicated that you merged the toggling of the filter into the code and built it.  When I got in today I pulled the latest build for 03-18-2015 and the toggling of the filter still isn't functioning.  Any help here would be appreciated.

Thanks,
    Scott R. Sonnenwald

**Comment by PaulL1** [comment] 2015-03-18 18:48
Is it working for you on the 105 tutorial?  Is the code you pulled the same as that included in the 105 tutorial?

**Comment by ssonnenwald** [comment] 2015-03-18 20:29
Yes, it is.  I finally got it to work by following that tutorial.  I had the toggle logic put in the ng-click binding like this example http://plnkr.co/edit/kQgpiHXbnJlklQOHzc3Z?p=preview and it didn't work.  When I put a function to be called on the controller it all worked fine.  Thanks for your help on this.  Much appreciated.

Scott R. Sonnenwald

**Comment by sendittokeith** [comment] 2016-01-29 19:22
I was just looking for this functionality as well.  I thought something was wrong with my code when this wasnt working:  vm.gridOptions.enableFiltering = !vm.gridOptions.enableFiltering;

The filtering is great but can easily distract from the beauty of the grid and is not needed all of the time.   It would be nice to simply toggle this value like we can with many of the other gridOptions.

**Comment by Leonardonline** [comment] 2016-10-19 10:18
I hope that after all this time is still useful.

The example referred to link [http://plnkr.co/edit/kQgpiHXbnJlklQOHzc3Z?p=preview](url) does not work because it lacks the following property

```javascript
...
onRegisterApi: function(gridApi){
      $scope.gridApi = gridApi;
    },
```


And the ng-click of the button need to call a function

```html
<button ng-click="toggleFilter()">Toggle Filter</button>
```

```javascript
$scope.toggleFilter = function() {
    $scope.gridOptions.enableFiltering = !$scope.gridOptions.enableFiltering;
    $scope.gridApi.core.notifyDataChange(uiGridConstants.dataChange.COLUMN);
  }
```

**Comment by nsksaisaravana** [comment] 2018-06-08 01:00
@Leonardonline tons of thanks and you saved my day.
