### ISSUE TITLE
ui-grid-move-columns along with ui-grid-selection making issue in column animation 

### ISSUE THREAD

**Issue by bvsbharat** [angular-ui/ng-grid#3477] opened 2015-05-12 05:13 UTC
Hi when i used both the directives it making issue in moving column animation,  ui-grid-move-columns along with ui-grid-selection making issue in column animation.

**Comment by PaulL1** [comment] 2015-05-16 05:27
Duplicate of #3395

**Closed** 2015-06-12 14:18 UTC
Labels: duplicate
