### ISSUE TITLE
Can we improve scrolling on this grid?

### ISSUE THREAD

**Issue by mikehuebner** [angular-ui/ng-grid#2467] opened 2014-12-31 02:52 UTC
I see you have a ton of issues going on Github already, so instead of actually reporting the issue I want to try to fix it!

I'm using your grid on an upcoming project and I love using it! The features are rich and well done, there are just so many issues with scrolling the grid and wanted to know how to fix this!

Focusing the grid and scrolling messes things up, scrolling in general is jumpy and just doesn't feel natural and its crazy trying to scroll both directions and keep track of where you were due to the jumpy scrolling.

What can I do to fix some of these issues or turn off this style scrolling? I noticed with NG-Grid on the old website you guys have, scrolling is awesome on that and wondered if I should just roll back to that or try to fix this one!

Any information on this would be helpful! (Code location, CSS issue maybe? Viewport issue?)

**Comment by mikehuebner** [comment] 2015-01-03 02:07
I've only come across scrolling during edit won't let you scroll, just keeps reverting to the original position of where the edit happened. I'll look into it in a bit, that seems like a bigger problem than a scroll lag. But I noticed a couple days ago searching through the code there are around 1k plus listeners on the grid alone, not including any other dependencies that get added to the grid. That could be the source of the scrolling lag, but it seems that those are all mandatory for the grid (just speaking obviously here). Is there any way to execute those over certain actions instead of all at once? Like as the events come into play, maybe even break down the listener events. I didn't write this so I could be 110% wrong with everything I'm saying, if I am correct me please!

**Comment by morungos** [comment] 2015-01-07 17:38
I've seen this too. It's even in the tutorial: http://ui-grid.info/docs/#/tutorial/301_editableOnFocus. Even if a cell is selected (and not edited) scrolling re-fires an event which makes it start editing. I'd actually be happy if I could deselect a cell so that didn't happen. However, I'm fairly sure that scrolling should not initiate a new edit even on a selected cell. 

I've comply commented out the second line below:

```
// Re-broadcast a cellNav event so we re-focus the right cell
// uiGridCtrl.cellNav.broadcastCellNav(lastRowCol);
```

And this appears to resolve the issue for me. Even if there are focusing issues, they are less bad than the broken scroll/edit combination.

**Comment by PaulL1** [comment] 2015-01-08 22:26
There's a change merging shortly that will probably address some of the scrolling issues, it certainly improves a bunch of things.  Could you take a look again to see if it addresses your concerns?

**Comment by PaulL1** [comment] 2015-01-14 19:58
I think the remaining issues in here are a duplicate of #2423

**Closed** 2015-02-26 07:43 UTC
Labels: enhancement, waiting-response
