### ISSUE TITLE
ui-grid Columns Headings are not properly aligned in IE9

### ISSUE THREAD

**Issue by siraj444** [angular-ui/ng-grid#3856] opened 2015-06-24 18:02 UTC
Hi, i am having issue with ui-grid misalignment of columns titles in Internet Explorer 9 as shown in the following picture. It works ok in firefox and Chrome but not in IE9 and 10.

![ui-grid-ie9issue](https://cloud.githubusercontent.com/assets/4791518/8337449/2e13dd48-1a79-11e5-8030-27135b410a1e.png)

This issue can be observed by resizing the columns in following link using IE9:
http://ui-grid.info/docs/#/tutorial/204_column_resizing

I would appreciate if somebody has any idea why is this and what's the solution.

**Comment by JLLeitschuh** [comment] 2015-06-24 20:27
Closing as this is a duplicate of #3854

**Closed by JLLeitschuh** 2015-06-24 20:27 UTC
Labels: duplicate
