### ISSUE TITLE
No more grid menus in all tutorials after last commit 

### ISSUE THREAD

**Issue by yurigenin** [angular-ui/ng-grid#3167] opened 2015-03-31 00:36 UTC
Check any tutorial and no headers have their menus and sort indicators any longer

**Comment by PaulL1** [comment] 2015-03-31 01:16
Duplicate of #3165.  The issue is that the fonts are broken.  This looks to be a build process issue, the same code built locally works fine.

**Closed by PaulL1** 2015-03-31 01:16 UTC
Labels: duplicate
