### ISSUE TITLE
IE9 Tree View UI Problem

### ISSUE THREAD

**Issue by dereklin** [angular-ui/ng-grid#3434] opened 2015-05-06 17:33 UTC
I wonder if ui grid supports IE9.  There are a lot of issues using it in IE9.

In this case, the tree view expand/collapse buttons are out of place.  In the tutorial page, http://ui-grid.info/docs/#/tutorial/215_treeView, they don't even show when using IE9.

Is there any plan to fix these issues for IE9?

**Comment by AgDude** [comment] 2015-05-06 17:47
I haven't tried to reproduce it, but this appears to be the same issue as #3412

**Comment by PaulL1** [comment] 2015-05-16 02:56
IE9 support is patchy.  We have talked about desupporting IE9, because there are too many issues, but for now we're saying it's mostly there but not perfect.  But I think it is probably #3412 that you have a  problem with, and that happens on all browsers.

**Comment by PaulL1** [comment] 2015-06-06 01:08
Solution provided that may resolve this issue, no comment for 3 weeks, closing, please re-raise or reopen if this is still occurring.

**Closed by PaulL1** 2015-06-06 01:08 UTC
Labels: waiting-response
