### ISSUE TITLE
Selection column remain in left when I bound the dir attribute to scope

### ISSUE THREAD

**Issue by pooyaho** [angular-ui/ng-grid#2936] opened 2015-03-07 09:57 UTC
Hi

When I bind the dir attribute to the a variable in scope, With all values of the variable, Checkbox column for selection of row, remains to left. How can I solve this problem?

**Comment by PaulL1** [comment] 2015-03-10 07:28
I think you need to try again to articulate what your problem is, and perhaps provide a plunker.  At the moment I can't quite understand what it is that you've done, what about that you consider to be wrong, and what you expected it to do instead.

**Comment by c0bra** [comment] 2015-03-30 20:39
I think I understand the problem. When the grid initializes, it juses `Grid.addRowHeaderColumn()` to populate one of the pinned containers with the row selection buttons.

The problem is that if you update the direction of the grid, nothing is watching that property to re-initialize it. So after you switch directions, the row header column is still in the same container and not the opposite one of what it should have been.

This is a larger problem than it seems. What we're talking about is the need to re-initialize all sorts of features/behaviors in the grid based on arbitrary properties.

@pooyaho What exactly is your use case that you need to switch from LTR to RTL live? Are you changing languages without reloading the page?

**Comment by PaulL1** [comment] 2015-04-21 08:33
No further comment for 3 weeks - I suspect issue has been resolved by not changing this property once the grid is rendered.  Closing.

**Closed by PaulL1** 2015-04-21 08:33 UTC
Labels: enhancement, waiting-response

**Comment by pooyaho** [comment] 2015-05-20 14:27
it is too simple, just bind the direction of the grid to a model and change the model. you'll see that the selection column remains in left
