### ISSUE TITLE
Pagination mode: page does not scroll when mouse pointer lies on grid

### ISSUE THREAD

**Issue by dinko** [angular-ui/ng-grid#2062] opened 2014-11-11 15:02 UTC
Using Chrome on Mac OS X.

On a given page, there's a grid and you have to scroll the page to reach it. Once you reach the grid, you will likely put the mouse pointer over the grid. In scrolling mode (as opposed to pagination mode) this is certainly the desired behavior as the grid needs to be scrollable.

However, when reaching the vertical end of a grid the scroll stops as opposed to that it's now transferred to the page, which may be the expected behavior (similar to scrolling iframe or divs). This makes it more difficult to reach content that lies below the grid.

In pagination mode, the this vertical scrolling "block" would not be necessary at all as in pagination I don't desire vertical scrolling anyway.

You can reproduce this issue easily on the [two grids tutorial page] (http://ui-grid.info/docs/#/tutorial/211_two_grids). Just find the first grid, move the mouse over it, scroll to the end of the grid and when you reach the end, you will notice the scroll stops.

**Comment by PaulL1** [comment] 2015-01-14 22:27
I think this is now resolved - could you restest?

**Comment by dinko** [comment] 2015-01-15 13:58
I tested again (OSX 10.9.5 on Chrome 39.0.2171.95, see
https://www.dropbox.com/s/355gjm735hn8dtn/2062.mov?dl=0

It seems to work now when scrolling up within the grid and reaching the upper ed, but not when scrolling down and reaching the lower end.

**Comment by PaulL1** [comment] 2015-01-15 18:12
Perhaps a duplicate of #1926

**Comment by dinko** [comment] 2015-01-15 20:00
Yes, agree, that's a duplicate.

**Closed** 2015-01-15 20:25 UTC
Labels: bug
