### ISSUE TITLE
enableCellEditOnFocus for date objects cells has a weird behavior

### ISSUE THREAD

**Issue by adilbenmoussa** [angular-ui/ng-grid#2750] opened 2015-02-11 15:04 UTC
Hi Guys,

We are newbies on the ui-grid, and we are facing an issue with inline editing of the a date object cell. please check this plnkr: http://plnkr.co/edit/Zh8dh6CBifaCwFHxct63?p=preview

In my application i'm getting the behavior when the cell is edit mode and the user tries to scroll.

Tested on:
Chrome: Version 40.0.2214.111 (64-bit)
Safari: Version 8.0.3 (10600.3.18)

Thanx in advance!
Kind regards,

**Comment by PaulL1** [comment] 2015-02-11 18:53
This should be fixed in #2751, which I pushed this morning.

**Comment by axelstudios** [comment] 2015-02-11 22:45
@PaulL1 Looks like #2751 fixed part of the problem, but try editing a cell in [tutorial 309](http://ui-grid.info/docs/#/tutorial/309_editable_with_cellnav) after scrolling down

**Comment by adilbenmoussa** [comment] 2015-02-13 08:08
Hi @axelstudios I noticed that as well, an issue has been fired #2755 for that scenario.

regards,
Adil

**Comment by c0bra** [comment] 2015-02-24 14:56
@axelstudios I'm not seeing a problem on 309 currently. Can you confirm?

**Comment by axelstudios** [comment] 2015-02-24 15:46
Confirmed, editing after scrolling is working correctly.

**Comment by c0bra** [comment] 2015-02-24 17:33
Great, thank you!

**Closed** 2015-02-24 17:33 UTC
Labels: bug, waiting-response
