### ISSUE TITLE
Edit in place fails when scroll rows

### ISSUE THREAD

**Issue by pitymaia** [angular-ui/ng-grid#2773] opened 2015-02-13 13:39 UTC
Hi, there is a bug with edit in place, it fails if try edit a row after scroll.
It is impossible to edit any field after use the scroll bar. It only works if we are on the top of the table.

**Comment by PaulL1** [comment] 2015-02-13 23:34
Duplicate of #2755

**Closed** 2015-02-13 23:35 UTC
Labels: duplicate
