### ISSUE TITLE
expandable grid gets into unusable state when bottom rows are expanded and you scroll up

### ISSUE THREAD

**Issue by majgis** [angular-ui/ng-grid#2488] opened 2015-01-05 20:03 UTC
The expandable grid gets into an unusable state when you expand a bottom row and scroll up.

This issue is more pronounced on my local project which has a sub-grid with many rows.  It can be reproduced on the UI Grid tutorial page by expanding a couple bottom rows:

1. Go to expandable grid tutorial page: http://ui-grid.info/docs/#/tutorial/306_expandable_grid
2. Scroll to the bottom and expand the last two rows, 498 and 499
3. Start scrolling up
4. Notice that half the rows are now missing and they do not return until scrolling all the way back down to the bottom

**Comment by majgis** [comment] 2015-01-08 22:30
Here, we have some bottom rows expanded, everything is working as expected:
![image](https://cloud.githubusercontent.com/assets/546259/5672103/d6db28bc-974a-11e4-9327-e3ed1f0670d0.png)

Now, if you scroll up, the bottom rows disappear:
![image](https://cloud.githubusercontent.com/assets/546259/5672116/0ec33c9c-974b-11e4-8b24-6aad18b24e64.png)

**Comment by PaulL1** [comment] 2015-01-20 07:00
@jpuri, have you seen this behaviour before?

**Comment by jpuri** [comment] 2015-01-20 07:48
Hi @PaulL1 ,
Yep scrolling sometimes gives this behavior with expandable rows. But I am not sure how we can really fix it.

**Comment by c0bra** [comment] 2015-02-16 22:57
It looks like maybe the grid is short-changing the number of rows it thinks it can render

**Comment by jpuri** [comment] 2015-02-18 06:25
Hi @c0bra ,
I will check scroll logic for expandable grids.

**Comment by PaulL1** [comment] 2015-03-28 08:56
This appears resolved - could you confirm?

**Comment by PaulL1** [comment] 2015-03-28 23:01
And FYI @majgis: I think the example shots you provided would be a better use case for grouping rather than expandable.

**Comment by PaulL1** [comment] 2015-04-12 07:00
Or potentially the new treeView feature may also be useful here.

Closing, as this appears resolved and no further comment for some weeks.

**Closed by PaulL1** 2015-04-12 07:00 UTC
Labels: waiting-response

**Comment by amoskalov** [comment] 2016-03-30 08:50
Hi guys. Still can reproduce this on demo page http://ui-grid.info/docs/#/tutorial/216_expandable_grid
![expandable-scroll-issue](https://cloud.githubusercontent.com/assets/3035158/14136808/7c6c0e54-f66d-11e5-9ad6-7e8030881cb6.png)

**Comment by johnico** [comment] 2016-05-25 05:06
Still exist- there is an estimation to solve it?

**Comment by jgrier93** [comment] 2016-08-03 08:25
Hi, still experiencing this issue and can still recreate it on the demo page. Any update?

**Comment by EdgarDelaRosa** [comment] 2017-04-07 03:32
Experiencing the same issue.  Any potential fixes?
